// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 33;
#[doc = "Common Open Policy Service (COPS) Protocol"]
pub mod cops;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "cops-parameters",
    title: "Common Open Policy Service (COPS) Protocol",
    registries: cops::REGISTRIES,
}];
