// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "FLUTE - File Delivery over Unidirectional Transport (FLUTE) Parameters"]
pub mod flute;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "flute-parameters",
    title: "FLUTE - File Delivery over Unidirectional Transport (FLUTE) Parameters",
    registries: flute::REGISTRIES,
}];
