// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "IPS Protocol# (Protocol Number) Field"]
pub mod ips_protocols;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "ips-protocols",
    title: "IPS Protocol# (Protocol Number) Field",
    registries: ips_protocols::REGISTRIES,
}];
