// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 2;
pub const REGISTRY_COUNT: usize = 17;
#[cfg(feature = "smtp")]
#[doc = "Simple Mail Transfer Protocol (SMTP)"]
pub mod smtp;
#[cfg(feature = "smtp-enhanced-status-codes")]
#[doc = "Simple Mail Transfer Protocol (SMTP) Enhanced Status Codes Registry"]
pub mod smtp_enhanced_status_codes;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "smtp")]
    crate::RegistryGroup {
        id: "smtp",
        title: "Simple Mail Transfer Protocol (SMTP)",
        registries: smtp::REGISTRIES,
    },
    #[cfg(feature = "smtp-enhanced-status-codes")]
    crate::RegistryGroup {
        id: "smtp-enhanced-status-codes",
        title: "Simple Mail Transfer Protocol (SMTP) Enhanced Status Codes Registry",
        registries: smtp_enhanced_status_codes::REGISTRIES,
    },
];
