// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 3;
#[doc = "XML Evidence Record Syntax (XMLERS)"]
pub mod xmlers;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "xmlers",
    title: "XML Evidence Record Syntax (XMLERS)",
    registries: xmlers::REGISTRIES,
}];
