// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "Transfer Encodings"]
pub mod transfer_encodings;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "transfer-encodings",
    title: "Transfer Encodings",
    registries: transfer_encodings::REGISTRIES,
}];
