// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 3;
#[doc = "Messaging Abuse Reporting Format (MARF) Parameters"]
pub mod marf;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "marf-parameters",
    title: "Messaging Abuse Reporting Format (MARF) Parameters",
    registries: marf::REGISTRIES,
}];
