// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 5;
#[doc = "Locally-Served DNS Zones"]
pub mod locally_served_dns_zones;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "locally-served-dns-zones",
    title: "Locally-Served DNS Zones",
    registries: locally_served_dns_zones::REGISTRIES,
}];
