// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 18;
#[doc = "Open Shortest Path First v2 (OSPFv2) Parameters"]
pub mod ospfv2;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "ospfv2-parameters",
    title: "Open Shortest Path First v2 (OSPFv2) Parameters",
    registries: ospfv2::REGISTRIES,
}];
