// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 4;
#[doc = "Global Switched Telephone Network (GSTN) Address Element Extensions in Email Services"]
pub mod gstn_extensions;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "gstn-extensions",
    title: "Global Switched Telephone Network (GSTN) Address Element Extensions in Email Services",
    registries: gstn_extensions::REGISTRIES,
}];
