// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "Instant Messaging SRV Protocol Label Registry"]
pub mod im_srv_labels;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "im-srv-labels",
    title: "Instant Messaging SRV Protocol Label Registry",
    registries: im_srv_labels::REGISTRIES,
}];
