// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 7;
#[doc = "Session Traversal Utilities for NAT (STUN) Parameters"]
pub mod stun;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "stun-parameters",
    title: "Session Traversal Utilities for NAT (STUN) Parameters",
    registries: stun::REGISTRIES,
}];
