// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 6;
#[doc = "Distributed Denial-of-Service Open Threat Signaling (DOTS) Signal Channel"]
pub mod dots;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "dots",
    title: "Distributed Denial-of-Service Open Threat Signaling (DOTS) Signal Channel",
    registries: dots::REGISTRIES,
}];
