// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 5;
pub const REGISTRY_COUNT: usize = 9;
#[cfg(feature = "svrloc-cryptographic-bsd")]
#[doc = "Service Location Protocol Version 2 (SLPv2) Cryptographic BSD Codes"]
pub mod svrloc_cryptographic_bsd;
#[cfg(feature = "svrloc-error-numbers")]
#[doc = "Service Location Protocol, Version 2 (SLPv2) Error Numbers"]
pub mod svrloc_error_numbers;
#[cfg(feature = "svrloc-extensions")]
#[doc = "Service Location Protocol Extensions, Version 2 (SLPv2)"]
pub mod svrloc_extensions;
#[cfg(feature = "svrloc-function-ids")]
#[doc = "Service Location Protocol, Version 2 (SLPv2) Function IDs"]
pub mod svrloc_function_ids;
#[cfg(feature = "svrloc-templates")]
#[doc = "Service Location Protocol, Version 2 (SLPv2) Templates"]
pub mod svrloc_templates;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "svrloc-cryptographic-bsd")]
    crate::RegistryGroup {
        id: "svrloc-cryptographic-bsd",
        title: "Service Location Protocol Version 2 (SLPv2) Cryptographic BSD Codes",
        registries: svrloc_cryptographic_bsd::REGISTRIES,
    },
    #[cfg(feature = "svrloc-error-numbers")]
    crate::RegistryGroup {
        id: "svrloc-error-numbers",
        title: "Service Location Protocol, Version 2 (SLPv2) Error Numbers",
        registries: svrloc_error_numbers::REGISTRIES,
    },
    #[cfg(feature = "svrloc-extensions")]
    crate::RegistryGroup {
        id: "svrloc-extensions",
        title: "Service Location Protocol Extensions, Version 2 (SLPv2)",
        registries: svrloc_extensions::REGISTRIES,
    },
    #[cfg(feature = "svrloc-function-ids")]
    crate::RegistryGroup {
        id: "svrloc-function-ids",
        title: "Service Location Protocol, Version 2 (SLPv2) Function IDs",
        registries: svrloc_function_ids::REGISTRIES,
    },
    #[cfg(feature = "svrloc-templates")]
    crate::RegistryGroup {
        id: "svrloc-templates",
        title: "Service Location Protocol, Version 2 (SLPv2) Templates",
        registries: svrloc_templates::REGISTRIES,
    },
];
