// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "DNSSEC Delegation Signer (DS) Resource Record (RR) Type Digest Algorithms"]
pub mod ds_rr_types;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "ds-rr-types",
    title: "DNSSEC Delegation Signer (DS) Resource Record (RR) Type Digest Algorithms",
    registries: ds_rr_types::REGISTRIES,
}];
