// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 9;
#[doc = "Tunnel Extensible Authentication Protocol (TEAP) Parameters"]
pub mod teap;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "teap-parameters",
    title: "Tunnel Extensible Authentication Protocol (TEAP) Parameters",
    registries: teap::REGISTRIES,
}];
