// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 4;
pub const REGISTRY_COUNT: usize = 24;
#[cfg(feature = "dccp-parameters")]
#[doc = "Datagram Congestion Control Protocol (DCCP) Parameters"]
pub mod dccp;
#[cfg(feature = "dccp-ccid2-parameters")]
#[doc = "Profile for Datagram Congestion Control Protocol (DCCP) Congestion Control ID 2: TCP-like Congestion Control Parameters"]
pub mod dccp_ccid2;
#[cfg(feature = "dccp-ccid3-parameters")]
#[doc = "Profile for Datagram Congestion Control Protocol (DCCP) Congestion Control ID 3: TFRC Congestion Control Parameters"]
pub mod dccp_ccid3;
#[cfg(feature = "dccp-ccid4-parameters")]
#[doc = "Profile for Datagram Congestion Control Protocol (DCCP) Congestion Control ID 4: TCP-Friendly Rate Control for Small Packets (TFRC-SP)"]
pub mod dccp_ccid4;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "dccp-ccid2-parameters")]
    crate::RegistryGroup {
        id: "dccp-ccid2-parameters",
        title: "Profile for Datagram Congestion Control Protocol (DCCP) Congestion Control ID 2: TCP-like Congestion Control Parameters",
        registries: dccp_ccid2::REGISTRIES,
    },
    #[cfg(feature = "dccp-ccid3-parameters")]
    crate::RegistryGroup {
        id: "dccp-ccid3-parameters",
        title: "Profile for Datagram Congestion Control Protocol (DCCP) Congestion Control ID 3: TFRC Congestion Control Parameters",
        registries: dccp_ccid3::REGISTRIES,
    },
    #[cfg(feature = "dccp-ccid4-parameters")]
    crate::RegistryGroup {
        id: "dccp-ccid4-parameters",
        title: "Profile for Datagram Congestion Control Protocol (DCCP) Congestion Control ID 4: TCP-Friendly Rate Control for Small Packets (TFRC-SP)",
        registries: dccp_ccid4::REGISTRIES,
    },
    #[cfg(feature = "dccp-parameters")]
    crate::RegistryGroup {
        id: "dccp-parameters",
        title: "Datagram Congestion Control Protocol (DCCP) Parameters",
        registries: dccp::REGISTRIES,
    },
];
