// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 18;
#[doc = "Real-Time Streaming Protocol (RTSP) 2.0 Parameters"]
pub mod rtspv2;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "rtspv2-parameters",
    title: "Real-Time Streaming Protocol (RTSP) 2.0 Parameters",
    registries: rtspv2::REGISTRIES,
}];
