// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 3;
pub const REGISTRY_COUNT: usize = 6;
#[cfg(feature = "hoba-device-identifiers")]
#[doc = "HTTP Origin-Bound Authentication (HOBA) Device Identifier Types"]
pub mod hoba_device_identifiers;
#[cfg(feature = "hoba-key-identifiers")]
#[doc = "HTTP Origin-Bound Authentication (HOBA) Key Identifier Types"]
pub mod hoba_key_identifiers;
#[cfg(feature = "hoba-signature-algorithms")]
#[doc = "HTTP Origin-Bound Authentication (HOBA) Signature Algorithms"]
pub mod hoba_signature_algorithms;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "hoba-device-identifiers")]
    crate::RegistryGroup {
        id: "hoba-device-identifiers",
        title: "HTTP Origin-Bound Authentication (HOBA) Device Identifier Types",
        registries: hoba_device_identifiers::REGISTRIES,
    },
    #[cfg(feature = "hoba-key-identifiers")]
    crate::RegistryGroup {
        id: "hoba-key-identifiers",
        title: "HTTP Origin-Bound Authentication (HOBA) Key Identifier Types",
        registries: hoba_key_identifiers::REGISTRIES,
    },
    #[cfg(feature = "hoba-signature-algorithms")]
    crate::RegistryGroup {
        id: "hoba-signature-algorithms",
        title: "HTTP Origin-Bound Authentication (HOBA) Signature Algorithms",
        registries: hoba_signature_algorithms::REGISTRIES,
    },
];
