// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 7;
pub const REGISTRY_COUNT: usize = 108;
#[cfg(feature = "bgp-parameters")]
#[doc = "Border Gateway Protocol (BGP) Parameters"]
pub mod bgp;
#[cfg(feature = "bgp-data-collection-communities-std")]
#[doc = "Border Gateway Protocol (BGP) Data Collection Standard Communities"]
pub mod bgp_data_collection_communities_std;
#[cfg(feature = "bgp-extended-communities")]
#[doc = "Border Gateway Protocol (BGP) Extended Communities"]
pub mod bgp_extended_communities;
#[cfg(feature = "bgp-ls-parameters")]
#[doc = "Border Gateway Protocol - Link State (BGP-LS) Parameters"]
pub mod bgp_ls;
#[cfg(feature = "bgp-spf")]
#[doc = "BGP Shortest Path First (BGP SPF)"]
pub mod bgp_spf;
#[cfg(feature = "bgp-tunnel-encapsulation")]
#[doc = "Border Gateway Protocol (BGP) Tunnel Encapsulation"]
pub mod bgp_tunnel_encapsulation;
#[cfg(feature = "bgp-well-known-communities")]
#[doc = "Border Gateway Protocol (BGP) Well-known Communities"]
pub mod bgp_well_known_communities;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "bgp-data-collection-communities-std")]
    crate::RegistryGroup {
        id: "bgp-data-collection-communities-std",
        title: "Border Gateway Protocol (BGP) Data Collection Standard Communities",
        registries: bgp_data_collection_communities_std::REGISTRIES,
    },
    #[cfg(feature = "bgp-extended-communities")]
    crate::RegistryGroup {
        id: "bgp-extended-communities",
        title: "Border Gateway Protocol (BGP) Extended Communities",
        registries: bgp_extended_communities::REGISTRIES,
    },
    #[cfg(feature = "bgp-ls-parameters")]
    crate::RegistryGroup {
        id: "bgp-ls-parameters",
        title: "Border Gateway Protocol - Link State (BGP-LS) Parameters",
        registries: bgp_ls::REGISTRIES,
    },
    #[cfg(feature = "bgp-parameters")]
    crate::RegistryGroup {
        id: "bgp-parameters",
        title: "Border Gateway Protocol (BGP) Parameters",
        registries: bgp::REGISTRIES,
    },
    #[cfg(feature = "bgp-spf")]
    crate::RegistryGroup {
        id: "bgp-spf",
        title: "BGP Shortest Path First (BGP SPF)",
        registries: bgp_spf::REGISTRIES,
    },
    #[cfg(feature = "bgp-tunnel-encapsulation")]
    crate::RegistryGroup {
        id: "bgp-tunnel-encapsulation",
        title: "Border Gateway Protocol (BGP) Tunnel Encapsulation",
        registries: bgp_tunnel_encapsulation::REGISTRIES,
    },
    #[cfg(feature = "bgp-well-known-communities")]
    crate::RegistryGroup {
        id: "bgp-well-known-communities",
        title: "Border Gateway Protocol (BGP) Well-known Communities",
        registries: bgp_well_known_communities::REGISTRIES,
    },
];
