// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 7;
#[doc = "Megaco/H.248 Packages"]
pub mod megaco_h248;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "megaco-h248",
    title: "Megaco/H.248 Packages",
    registries: megaco_h248::REGISTRIES,
}];
