// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "Service Location Protocol (SLP) Remote Service Discovery"]
pub mod slp_da_service;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "slp-da-service",
    title: "Service Location Protocol (SLP) Remote Service Discovery",
    registries: slp_da_service::REGISTRIES,
}];
