// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "Instant Message Disposition Notification (IMDN) Headers"]
pub mod imdn;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "imdn",
    title: "Instant Message Disposition Notification (IMDN) Headers",
    registries: imdn::REGISTRIES,
}];
