// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 35;
#[doc = "Incident Object Description Exchange Format v2 (IODEF)"]
pub mod iodef2;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "iodef2",
    title: "Incident Object Description Exchange Format v2 (IODEF)",
    registries: iodef2::REGISTRIES,
}];
