// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 8;
#[doc = "Protocol for Carrying Authentication for Network Access (PANA) Parameters"]
pub mod pana;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "pana-parameters",
    title: "Protocol for Carrying Authentication for Network Access (PANA) Parameters",
    registries: pana::REGISTRIES,
}];
