// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 3;
#[doc = "Simple Authentication and Security Layer (SASL) Mechanisms"]
pub mod sasl_mechanisms;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "sasl-mechanisms",
    title: "Simple Authentication and Security Layer (SASL) Mechanisms",
    registries: sasl_mechanisms::REGISTRIES,
}];
