// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 2;
pub const REGISTRY_COUNT: usize = 4;
#[cfg(feature = "special-registry")]
#[doc = "Special People Numbers Registry (SPNR)"]
pub mod special_registry;
#[cfg(feature = "special-use-domain-names")]
#[doc = "Special-Use Domain Names"]
pub mod special_use_domain_names;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "special-registry")]
    crate::RegistryGroup {
        id: "special-registry",
        title: "Special People Numbers Registry (SPNR)",
        registries: special_registry::REGISTRIES,
    },
    #[cfg(feature = "special-use-domain-names")]
    crate::RegistryGroup {
        id: "special-use-domain-names",
        title: "Special-Use Domain Names",
        registries: special_use_domain_names::REGISTRIES,
    },
];
