// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 8;
#[doc = "Service Function Chaining (SFC) Active Operations, Administration, and Maintenance (OAM)"]
pub mod sfc_active_oam;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "sfc-active-oam",
    title: "Service Function Chaining (SFC) Active Operations, Administration, and Maintenance (OAM)",
    registries: sfc_active_oam::REGISTRIES,
}];
