// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 2;
pub const REGISTRY_COUNT: usize = 5;
#[cfg(feature = "te-link-capabilities")]
#[doc = "Link State Routing TE Capabilities"]
pub mod te_link_capabilities;
#[cfg(feature = "te-types")]
#[doc = "Traffic Engineering (TE) LSA Types and Traffic Engineering (TE) TLVs"]
pub mod te_types;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "te-link-capabilities")]
    crate::RegistryGroup {
        id: "te-link-capabilities",
        title: "Link State Routing TE Capabilities",
        registries: te_link_capabilities::REGISTRIES,
    },
    #[cfg(feature = "te-types")]
    crate::RegistryGroup {
        id: "te-types",
        title: "Traffic Engineering (TE) LSA Types and Traffic Engineering (TE) TLVs",
        registries: te_types::REGISTRIES,
    },
];
