// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 3;
pub const REGISTRY_COUNT: usize = 144;
#[cfg(feature = "rsvp-parameters")]
#[doc = "Resource Reservation Protocol (RSVP) Parameters"]
pub mod rsvp;
#[cfg(feature = "rsvp-te-parameters")]
#[doc = "Resource Reservation Protocol-Traffic Engineering (RSVP-TE) Parameters"]
pub mod rsvp_te;
#[cfg(feature = "rsvp-te-oam")]
#[doc = "RSVP-TE OAM Configuration Registry"]
pub mod rsvp_te_oam;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "rsvp-parameters")]
    crate::RegistryGroup {
        id: "rsvp-parameters",
        title: "Resource Reservation Protocol (RSVP) Parameters",
        registries: rsvp::REGISTRIES,
    },
    #[cfg(feature = "rsvp-te-oam")]
    crate::RegistryGroup {
        id: "rsvp-te-oam",
        title: "RSVP-TE OAM Configuration Registry",
        registries: rsvp_te_oam::REGISTRIES,
    },
    #[cfg(feature = "rsvp-te-parameters")]
    crate::RegistryGroup {
        id: "rsvp-te-parameters",
        title: "Resource Reservation Protocol-Traffic Engineering (RSVP-TE) Parameters",
        registries: rsvp_te::REGISTRIES,
    },
];
