// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 2;
pub const REGISTRY_COUNT: usize = 12;
#[cfg(feature = "mrt")]
#[doc = "Multi-threaded Routing Toolkit (MRT)"]
pub mod mrt;
#[cfg(feature = "mrt-parameters")]
#[doc = "Maximally Redundant Tree (MRT) Parameters"]
pub mod mrt_parameters;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "mrt")]
    crate::RegistryGroup {
        id: "mrt",
        title: "Multi-threaded Routing Toolkit (MRT)",
        registries: mrt::REGISTRIES,
    },
    #[cfg(feature = "mrt-parameters")]
    crate::RegistryGroup {
        id: "mrt-parameters",
        title: "Maximally Redundant Tree (MRT) Parameters",
        registries: mrt_parameters::REGISTRIES,
    },
];
