// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 21;
#[doc = "NSIS Signaling Layer Protocol (NSLP) Parameters"]
pub mod nslp;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "nslp-parameters",
    title: "NSIS Signaling Layer Protocol (NSLP) Parameters",
    registries: nslp::REGISTRIES,
}];
