// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "AMTRELAY Resource Record Parameters"]
pub mod amtrelay_resource_record;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "amtrelay-resource-record",
    title: "AMTRELAY Resource Record Parameters",
    registries: amtrelay_resource_record::REGISTRIES,
}];
