// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 8;
pub const REGISTRY_COUNT: usize = 31;
#[cfg(feature = "ospf-parameters")]
#[doc = "Open Shortest Path First (OSPF) Parameters"]
pub mod ospf;
#[cfg(feature = "ospf-authentication-codes")]
#[doc = "Open Shortest Path First (OSPF) Authentication Codes"]
pub mod ospf_authentication_codes;
#[cfg(feature = "ospf-dd-packet-flags")]
#[doc = "OSPF Database Description (DD) Packet Flags"]
pub mod ospf_dd_packet_flags;
#[cfg(feature = "ospf-lls-tlvs")]
#[doc = "Open Shortest Path First (OSPF) Link Local Signalling (LLS) - Type/Length/Value Identifiers (TLV)"]
pub mod ospf_lls_tlvs;
#[cfg(feature = "ospf-mt-routing")]
#[doc = "Open Shortest Path First (OSPF) Multi-Topology Routing"]
pub mod ospf_mt_routing;
#[cfg(feature = "ospf-opaque-types")]
#[doc = "Open Shortest Path First (OSPF) Opaque Link-State Advertisements (LSA) Option Types"]
pub mod ospf_opaque_types;
#[cfg(feature = "ospf-sig-alg")]
#[doc = "Open Shortest Path First (OSPF) Signature Algorithms"]
pub mod ospf_sig_alg;
#[cfg(feature = "ospf-traffic-eng-tlvs")]
#[doc = "Open Shortest Path First (OSPF) Traffic Engineering TLVs"]
pub mod ospf_traffic_eng_tlvs;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "ospf-authentication-codes")]
    crate::RegistryGroup {
        id: "ospf-authentication-codes",
        title: "Open Shortest Path First (OSPF) Authentication Codes",
        registries: ospf_authentication_codes::REGISTRIES,
    },
    #[cfg(feature = "ospf-dd-packet-flags")]
    crate::RegistryGroup {
        id: "ospf-dd-packet-flags",
        title: "OSPF Database Description (DD) Packet Flags",
        registries: ospf_dd_packet_flags::REGISTRIES,
    },
    #[cfg(feature = "ospf-lls-tlvs")]
    crate::RegistryGroup {
        id: "ospf-lls-tlvs",
        title: "Open Shortest Path First (OSPF) Link Local Signalling (LLS) - Type/Length/Value Identifiers (TLV)",
        registries: ospf_lls_tlvs::REGISTRIES,
    },
    #[cfg(feature = "ospf-mt-routing")]
    crate::RegistryGroup {
        id: "ospf-mt-routing",
        title: "Open Shortest Path First (OSPF) Multi-Topology Routing",
        registries: ospf_mt_routing::REGISTRIES,
    },
    #[cfg(feature = "ospf-opaque-types")]
    crate::RegistryGroup {
        id: "ospf-opaque-types",
        title: "Open Shortest Path First (OSPF) Opaque Link-State Advertisements (LSA) Option Types",
        registries: ospf_opaque_types::REGISTRIES,
    },
    #[cfg(feature = "ospf-parameters")]
    crate::RegistryGroup {
        id: "ospf-parameters",
        title: "Open Shortest Path First (OSPF) Parameters",
        registries: ospf::REGISTRIES,
    },
    #[cfg(feature = "ospf-sig-alg")]
    crate::RegistryGroup {
        id: "ospf-sig-alg",
        title: "Open Shortest Path First (OSPF) Signature Algorithms",
        registries: ospf_sig_alg::REGISTRIES,
    },
    #[cfg(feature = "ospf-traffic-eng-tlvs")]
    crate::RegistryGroup {
        id: "ospf-traffic-eng-tlvs",
        title: "Open Shortest Path First (OSPF) Traffic Engineering TLVs",
        registries: ospf_traffic_eng_tlvs::REGISTRIES,
    },
];
