// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 7;
#[doc = "Peer-to-Peer Streaming Peer Protocol (PPSPP)"]
pub mod ppspp;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "ppspp",
    title: "Peer-to-Peer Streaming Peer Protocol (PPSPP)",
    registries: ppspp::REGISTRIES,
}];
