// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 3;
#[doc = "Domain-based Message Authentication, Reporting, and Conformance (DMARC)"]
pub mod dmarc;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "dmarc-parameters",
    title: "Domain-based Message Authentication, Reporting, and Conformance (DMARC)",
    registries: dmarc::REGISTRIES,
}];
