// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 19;
#[doc = "Telnet Options"]
pub mod telnet_options;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "telnet-options",
    title: "Telnet Options",
    registries: telnet_options::REGISTRIES,
}];
