// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "Provisional Standard Media Type Registry"]
pub mod provisional_standard_media_types;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "provisional-standard-media-types",
    title: "Provisional Standard Media Type Registry",
    registries: provisional_standard_media_types::REGISTRIES,
}];
