// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 11;
pub const REGISTRY_COUNT: usize = 17;
#[cfg(feature = "rdap-asn")]
#[doc = "Bootstrap Service Registry for AS Number Space"]
pub mod rdap_asn;
#[cfg(feature = "rdap-dns")]
#[doc = "Bootstrap Service Registry for Domain Name Space"]
pub mod rdap_dns;
#[cfg(feature = "rdap-extensions")]
#[doc = "RDAP Extensions"]
pub mod rdap_extensions;
#[cfg(feature = "rdap-ipv4")]
#[doc = "Bootstrap Service Registry for IPv4 Address Space"]
pub mod rdap_ipv4;
#[cfg(feature = "rdap-ipv6")]
#[doc = "Bootstrap Service Registry for IPv6 Address Space"]
pub mod rdap_ipv6;
#[cfg(feature = "rdap-json-values")]
#[doc = "RDAP JSON Values"]
pub mod rdap_json_values;
#[cfg(feature = "rdap-object-tags")]
#[doc = "Bootstrap Service Registry for Provider Object Tags"]
pub mod rdap_object_tags;
#[cfg(feature = "rdap-provider-object-tags")]
#[doc = "RDAP Provider Object Tags"]
pub mod rdap_provider_object_tags;
#[cfg(feature = "rdap-query-purpose-values")]
#[doc = "Registration Data Access Protocol (RDAP) Query Purpose Values"]
pub mod rdap_query_purpose_values;
#[cfg(feature = "rdap-reverse-search")]
#[doc = "RDAP Reverse Search"]
pub mod rdap_reverse_search;
#[cfg(feature = "rdap-reverse-search-mapping")]
#[doc = "RDAP Reverse Search Mapping"]
pub mod rdap_reverse_search_mapping;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "rdap-asn")]
    crate::RegistryGroup {
        id: "rdap-asn",
        title: "Bootstrap Service Registry for AS Number Space",
        registries: rdap_asn::REGISTRIES,
    },
    #[cfg(feature = "rdap-dns")]
    crate::RegistryGroup {
        id: "rdap-dns",
        title: "Bootstrap Service Registry for Domain Name Space",
        registries: rdap_dns::REGISTRIES,
    },
    #[cfg(feature = "rdap-extensions")]
    crate::RegistryGroup {
        id: "rdap-extensions",
        title: "RDAP Extensions",
        registries: rdap_extensions::REGISTRIES,
    },
    #[cfg(feature = "rdap-ipv4")]
    crate::RegistryGroup {
        id: "rdap-ipv4",
        title: "Bootstrap Service Registry for IPv4 Address Space",
        registries: rdap_ipv4::REGISTRIES,
    },
    #[cfg(feature = "rdap-ipv6")]
    crate::RegistryGroup {
        id: "rdap-ipv6",
        title: "Bootstrap Service Registry for IPv6 Address Space",
        registries: rdap_ipv6::REGISTRIES,
    },
    #[cfg(feature = "rdap-json-values")]
    crate::RegistryGroup {
        id: "rdap-json-values",
        title: "RDAP JSON Values",
        registries: rdap_json_values::REGISTRIES,
    },
    #[cfg(feature = "rdap-object-tags")]
    crate::RegistryGroup {
        id: "rdap-object-tags",
        title: "Bootstrap Service Registry for Provider Object Tags",
        registries: rdap_object_tags::REGISTRIES,
    },
    #[cfg(feature = "rdap-provider-object-tags")]
    crate::RegistryGroup {
        id: "rdap-provider-object-tags",
        title: "RDAP Provider Object Tags",
        registries: rdap_provider_object_tags::REGISTRIES,
    },
    #[cfg(feature = "rdap-query-purpose-values")]
    crate::RegistryGroup {
        id: "rdap-query-purpose-values",
        title: "Registration Data Access Protocol (RDAP) Query Purpose Values",
        registries: rdap_query_purpose_values::REGISTRIES,
    },
    #[cfg(feature = "rdap-reverse-search")]
    crate::RegistryGroup {
        id: "rdap-reverse-search",
        title: "RDAP Reverse Search",
        registries: rdap_reverse_search::REGISTRIES,
    },
    #[cfg(feature = "rdap-reverse-search-mapping")]
    crate::RegistryGroup {
        id: "rdap-reverse-search-mapping",
        title: "RDAP Reverse Search Mapping",
        registries: rdap_reverse_search_mapping::REGISTRIES,
    },
];
