// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "Open Systems Interconnection (OSI) Network Service Access Point Addresses (NSAPA) Internet Code Point Registry"]
pub mod osi_nsapa_numbers;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "osi-nsapa-numbers",
    title: "Open Systems Interconnection (OSI) Network Service Access Point Addresses (NSAPA) Internet Code Point Registry",
    registries: osi_nsapa_numbers::REGISTRIES,
}];
