// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 16;
#[doc = "Dynamic Link Exchange Protocol (DLEP) Parameters"]
pub mod dlep;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "dlep-parameters",
    title: "Dynamic Link Exchange Protocol (DLEP) Parameters",
    registries: dlep::REGISTRIES,
}];
