// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 17;
#[doc = "REsource LOcation And Discovery (RELOAD)"]
pub mod reload;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "reload",
    title: "REsource LOcation And Discovery (RELOAD)",
    registries: reload::REGISTRIES,
}];
