// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 4;
#[doc = "WAVE and AVI Codec Registries (Historic Registry)"]
pub mod wave_avi_codec_registry;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "wave-avi-codec-registry",
    title: "WAVE and AVI Codec Registries (Historic Registry)",
    registries: wave_avi_codec_registry::REGISTRIES,
}];
