// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 2;
pub const REGISTRY_COUNT: usize = 4;
#[cfg(feature = "rohc-pro-ids")]
#[doc = "RObust Header Compression (ROHC) Profile Identifiers"]
pub mod rohc_pro_ids;
#[cfg(feature = "rohc-sub-ids")]
#[doc = "RObust Header Compression (ROHC) Suboption Identifier Values"]
pub mod rohc_sub_ids;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "rohc-pro-ids")]
    crate::RegistryGroup {
        id: "rohc-pro-ids",
        title: "RObust Header Compression (ROHC) Profile Identifiers",
        registries: rohc_pro_ids::REGISTRIES,
    },
    #[cfg(feature = "rohc-sub-ids")]
    crate::RegistryGroup {
        id: "rohc-sub-ids",
        title: "RObust Header Compression (ROHC) Suboption Identifier Values",
        registries: rohc_sub_ids::REGISTRIES,
    },
];
