// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "Network Configuration Protocol (NETCONF) Capability URNs"]
pub mod netconf_capability_urns;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "netconf-capability-urns",
    title: "Network Configuration Protocol (NETCONF) Capability URNs",
    registries: netconf_capability_urns::REGISTRIES,
}];
