// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "SUN Remote Procedure Call (RPC) Numbers - Obsolete"]
pub mod sun_rpc_numbers;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "sun-rpc-numbers",
    title: "SUN Remote Procedure Call (RPC) Numbers - Obsolete",
    registries: sun_rpc_numbers::REGISTRIES,
}];
