// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 3;
pub const REGISTRY_COUNT: usize = 17;
#[cfg(feature = "tcp-parameters")]
#[doc = "Transmission Control Protocol (TCP) Parameters"]
pub mod tcp;
#[cfg(feature = "tcp-convert-protocol-parameters")]
#[doc = "TCP Convert Protocol (Convert) Parameters"]
pub mod tcp_convert_protocol;
#[cfg(feature = "tcp-header-flags")]
#[doc = "Transmission Control Protocol (TCP) Header Flags"]
pub mod tcp_header_flags;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "tcp-convert-protocol-parameters")]
    crate::RegistryGroup {
        id: "tcp-convert-protocol-parameters",
        title: "TCP Convert Protocol (Convert) Parameters",
        registries: tcp_convert_protocol::REGISTRIES,
    },
    #[cfg(feature = "tcp-header-flags")]
    crate::RegistryGroup {
        id: "tcp-header-flags",
        title: "Transmission Control Protocol (TCP) Header Flags",
        registries: tcp_header_flags::REGISTRIES,
    },
    #[cfg(feature = "tcp-parameters")]
    crate::RegistryGroup {
        id: "tcp-parameters",
        title: "Transmission Control Protocol (TCP) Parameters",
        registries: tcp::REGISTRIES,
    },
];
