// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 2;
pub const REGISTRY_COUNT: usize = 5;
#[cfg(feature = "auto-response-parameters")]
#[doc = "Automatic Responses to Electronic Mail Parameters"]
pub mod auto_response;
#[cfg(feature = "auto-submitted-keywords")]
#[doc = "Auto-Submitted Header Field Keywords"]
pub mod auto_submitted_keywords;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "auto-response-parameters")]
    crate::RegistryGroup {
        id: "auto-response-parameters",
        title: "Automatic Responses to Electronic Mail Parameters",
        registries: auto_response::REGISTRIES,
    },
    #[cfg(feature = "auto-submitted-keywords")]
    crate::RegistryGroup {
        id: "auto-submitted-keywords",
        title: "Auto-Submitted Header Field Keywords",
        registries: auto_submitted_keywords::REGISTRIES,
    },
];
