// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 4;
#[doc = "RPCBIND Transport Parameters"]
pub mod rpcbind_transport;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "rpcbind-transport-parameters",
    title: "RPCBIND Transport Parameters",
    registries: rpcbind_transport::REGISTRIES,
}];
