// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 2;
pub const REGISTRY_COUNT: usize = 15;
#[cfg(feature = "kerberos-parameters")]
#[doc = "Kerberos Parameters"]
pub mod kerberos;
#[cfg(feature = "kerberos-v-gss-api")]
#[doc = "Kerberos V GSS-API Mechanism Parameters"]
pub mod kerberos_v_gss_api;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "kerberos-parameters")]
    crate::RegistryGroup {
        id: "kerberos-parameters",
        title: "Kerberos Parameters",
        registries: kerberos::REGISTRIES,
    },
    #[cfg(feature = "kerberos-v-gss-api")]
    crate::RegistryGroup {
        id: "kerberos-v-gss-api",
        title: "Kerberos V GSS-API Mechanism Parameters",
        registries: kerberos_v_gss_api::REGISTRIES,
    },
];
