// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 29;
#[doc = "Secure Shell (SSH) Protocol Parameters"]
pub mod ssh;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "ssh-parameters",
    title: "Secure Shell (SSH) Protocol Parameters",
    registries: ssh::REGISTRIES,
}];
