// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "SIG (0) Algorithm Numbers"]
pub mod sig_alg_numbers;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "sig-alg-numbers",
    title: "SIG (0) Algorithm Numbers",
    registries: sig_alg_numbers::REGISTRIES,
}];
