// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "Simple Gateway Monitoring Protocol (SGMP) Vendor Specific Codes (Obsolete)"]
pub mod sgmp_vendor_specific_codes;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "sgmp-vendor-specific-codes",
    title: "Simple Gateway Monitoring Protocol (SGMP) Vendor Specific Codes (Obsolete)",
    registries: sgmp_vendor_specific_codes::REGISTRIES,
}];
