// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 25;
#[doc = "Pseudowire Name Spaces (PWE3)"]
pub mod pwe3;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "pwe3-parameters",
    title: "Pseudowire Name Spaces (PWE3)",
    registries: pwe3::REGISTRIES,
}];
