// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 9;
#[doc = "Access Node Control Protocol (ANCP)"]
pub mod ancp;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "ancp",
    title: "Access Node Control Protocol (ANCP)",
    registries: ancp::REGISTRIES,
}];
