// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 23;
#[doc = "\"Magic Numbers\" for ISAKMP Protocol"]
pub mod isakmp_registry;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "isakmp-registry",
    title: "\"Magic Numbers\" for ISAKMP Protocol",
    registries: isakmp_registry::REGISTRIES,
}];
