// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 30;
#[doc = "Transparent Interconnection of Lots of Links (TRILL) Parameters"]
pub mod trill;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "trill-parameters",
    title: "Transparent Interconnection of Lots of Links (TRILL) Parameters",
    registries: trill::REGISTRIES,
}];
