// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 6;
pub const REGISTRY_COUNT: usize = 54;
#[cfg(feature = "media-control-channel")]
#[doc = "Media Control Channel Framework Parameters"]
pub mod media_control_channel;
#[cfg(feature = "media-feature-tags")]
#[doc = "Media Feature Tags - iso.org.dod.internet.features (1.3.6.1.8)"]
pub mod media_feature_tags;
#[cfg(feature = "media-type-structured-suffix")]
#[doc = "Structured Syntax Suffixes"]
pub mod media_type_structured_suffix;
#[cfg(feature = "media-type-sub-parameters")]
#[doc = "Media Type Sub-Parameter Registries"]
pub mod media_type_sub;
#[cfg(feature = "media-types")]
#[doc = "Media Types"]
pub mod media_types;
#[cfg(feature = "media-types-parameters")]
#[doc = "MIME Media Type Parameters"]
pub mod media_types_parameters;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "media-control-channel")]
    crate::RegistryGroup {
        id: "media-control-channel",
        title: "Media Control Channel Framework Parameters",
        registries: media_control_channel::REGISTRIES,
    },
    #[cfg(feature = "media-feature-tags")]
    crate::RegistryGroup {
        id: "media-feature-tags",
        title: "Media Feature Tags - iso.org.dod.internet.features (1.3.6.1.8)",
        registries: media_feature_tags::REGISTRIES,
    },
    #[cfg(feature = "media-type-structured-suffix")]
    crate::RegistryGroup {
        id: "media-type-structured-suffix",
        title: "Structured Syntax Suffixes",
        registries: media_type_structured_suffix::REGISTRIES,
    },
    #[cfg(feature = "media-type-sub-parameters")]
    crate::RegistryGroup {
        id: "media-type-sub-parameters",
        title: "Media Type Sub-Parameter Registries",
        registries: media_type_sub::REGISTRIES,
    },
    #[cfg(feature = "media-types")]
    crate::RegistryGroup {
        id: "media-types",
        title: "Media Types",
        registries: media_types::REGISTRIES,
    },
    #[cfg(feature = "media-types-parameters")]
    crate::RegistryGroup {
        id: "media-types-parameters",
        title: "MIME Media Type Parameters",
        registries: media_types_parameters::REGISTRIES,
    },
];
