// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 18;
#[doc = "Group Secure Association Group Management Protocol (GSAKMP) Parameters"]
pub mod gsakmp;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "gsakmp-parameters",
    title: "Group Secure Association Group Management Protocol (GSAKMP) Parameters",
    registries: gsakmp::REGISTRIES,
}];
