// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 3;
pub const REGISTRY_COUNT: usize = 6;
#[cfg(feature = "epp-extension-role-values")]
#[doc = "Extensible Provisioning Protocol (EPP) Organization Role Values"]
pub mod epp_extension_role_values;
#[cfg(feature = "epp-extensions")]
#[doc = "Extensions for the Extensible Provisioning Protocol (EPP)"]
pub mod epp_extensions;
#[cfg(feature = "epp-repository-ids")]
#[doc = "Extensible Provisioning Protocol (EPP) Repository Identifiers"]
pub mod epp_repository_ids;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "epp-extension-role-values")]
    crate::RegistryGroup {
        id: "epp-extension-role-values",
        title: "Extensible Provisioning Protocol (EPP) Organization Role Values",
        registries: epp_extension_role_values::REGISTRIES,
    },
    #[cfg(feature = "epp-extensions")]
    crate::RegistryGroup {
        id: "epp-extensions",
        title: "Extensions for the Extensible Provisioning Protocol (EPP)",
        registries: epp_extensions::REGISTRIES,
    },
    #[cfg(feature = "epp-repository-ids")]
    crate::RegistryGroup {
        id: "epp-repository-ids",
        title: "Extensible Provisioning Protocol (EPP) Repository Identifiers",
        registries: epp_repository_ids::REGISTRIES,
    },
];
