// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "ESP AGGFRAG_PAYLOAD"]
pub mod esp_aggfrag_payload;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "esp-aggfrag-payload",
    title: "ESP AGGFRAG_PAYLOAD",
    registries: esp_aggfrag_payload::REGISTRIES,
}];
