// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "Novell Service Advisor Protocol (SAP) Numbers - Novell Object Types"]
pub mod novell_sap_numbers;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "novell-sap-numbers",
    title: "Novell Service Advisor Protocol (SAP) Numbers - Novell Object Types",
    registries: novell_sap_numbers::REGISTRIES,
}];
