// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 4;
#[doc = "Message Session Relay Protocol (MSRP) Parameters"]
pub mod msrp;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "msrp-parameters",
    title: "Message Session Relay Protocol (MSRP) Parameters",
    registries: msrp::REGISTRIES,
}];
