// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 16;
#[doc = "Constrained RESTful Environments (CoRE) Parameters"]
pub mod core;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "core-parameters",
    title: "Constrained RESTful Environments (CoRE) Parameters",
    registries: core::REGISTRIES,
}];
