// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "STARTTLS Validation Result Types"]
pub mod starttls_validation_result_types;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "starttls-validation-result-types",
    title: "STARTTLS Validation Result Types",
    registries: starttls_validation_result_types::REGISTRIES,
}];
