// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 3;
#[doc = "Wrapped Encapsulating Security Payload (WESP) Flags"]
pub mod wesp_flags;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "wesp-flags",
    title: "Wrapped Encapsulating Security Payload (WESP) Flags",
    registries: wesp_flags::REGISTRIES,
}];
