// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "Presence SRV Protocol Label Registry"]
pub mod pres_srv_labels;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "pres-srv-labels",
    title: "Presence SRV Protocol Label Registry",
    registries: pres_srv_labels::REGISTRIES,
}];
