// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 15;
#[doc = "Dynamic Host Configuration Protocol for IPv6 (DHCPv6)"]
pub mod dhcpv6;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "dhcpv6-parameters",
    title: "Dynamic Host Configuration Protocol for IPv6 (DHCPv6)",
    registries: dhcpv6::REGISTRIES,
}];
