// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "Lightweight Directory Access Protocol (LDAP) - pcimSchema Descriptors"]
pub mod pcim_oids;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "pcim-oids",
    title: "Lightweight Directory Access Protocol (LDAP) - pcimSchema Descriptors",
    registries: pcim_oids::REGISTRIES,
}];
