// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 2;
pub const REGISTRY_COUNT: usize = 31;
#[cfg(feature = "sdp-parameters")]
#[doc = "Session Description Protocol (SDP) Parameters"]
pub mod sdp;
#[cfg(feature = "sdp-security-descriptions")]
#[doc = "Session Description Protocol (SDP) Security Descriptions"]
pub mod sdp_security_descriptions;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "sdp-parameters")]
    crate::RegistryGroup {
        id: "sdp-parameters",
        title: "Session Description Protocol (SDP) Parameters",
        registries: sdp::REGISTRIES,
    },
    #[cfg(feature = "sdp-security-descriptions")]
    crate::RegistryGroup {
        id: "sdp-security-descriptions",
        title: "Session Description Protocol (SDP) Security Descriptions",
        registries: sdp_security_descriptions::REGISTRIES,
    },
];
