// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 2;
pub const REGISTRY_COUNT: usize = 12;
#[cfg(feature = "cose")]
#[doc = "CBOR Object Signing and Encryption (COSE)"]
pub mod cose;
#[cfg(feature = "cose-suit-algorithm-profiles")]
#[doc = "COSE SUIT Algorithm Profiles"]
pub mod cose_suit_algorithm_profiles;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "cose")]
    crate::RegistryGroup {
        id: "cose",
        title: "CBOR Object Signing and Encryption (COSE)",
        registries: cose::REGISTRIES,
    },
    #[cfg(feature = "cose-suit-algorithm-profiles")]
    crate::RegistryGroup {
        id: "cose-suit-algorithm-profiles",
        title: "COSE SUIT Algorithm Profiles",
        registries: cose_suit_algorithm_profiles::REGISTRIES,
    },
];
