// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 33;
#[doc = "Point-to-Point (PPP) Protocol Field Assignments"]
pub mod ppp_numbers;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "ppp-numbers",
    title: "Point-to-Point (PPP) Protocol Field Assignments",
    registries: ppp_numbers::REGISTRIES,
}];
