// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 4;
#[doc = "Extensible Authentication Protocol Protected One-Time Password (EAP-POTP) Cryptographic Algorithm Identifiers"]
pub mod eappotp_identifiers;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "eappotp-identifiers",
    title: "Extensible Authentication Protocol Protected One-Time Password (EAP-POTP) Cryptographic Algorithm Identifiers",
    registries: eappotp_identifiers::REGISTRIES,
}];
