// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 4;
#[doc = "Electronic Commerce Modeling Language Version 2 (ECMLv2) Parameters"]
pub mod ecmlv2;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "ecmlv2-parameters",
    title: "Electronic Commerce Modeling Language Version 2 (ECMLv2) Parameters",
    registries: ecmlv2::REGISTRIES,
}];
