// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 4;
#[doc = "Public Key Infrastructure using X.509 (PKIX) Parameters"]
pub mod pkix;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "pkix-parameters",
    title: "Public Key Infrastructure using X.509 (PKIX) Parameters",
    registries: pkix::REGISTRIES,
}];
