// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "FTP Commands and Extensions"]
pub mod ftp_commands_extensions;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "ftp-commands-extensions",
    title: "FTP Commands and Extensions",
    registries: ftp_commands_extensions::REGISTRIES,
}];
