// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 10;
#[doc = "Realm Specific IP (RSIP) Parameters"]
pub mod rsip;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "rsip-parameters",
    title: "Realm Specific IP (RSIP) Parameters",
    registries: rsip::REGISTRIES,
}];
