// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 5;
#[doc = "IEEE 802 Numbers"]
pub mod ieee_802_numbers;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "ieee-802-numbers",
    title: "IEEE 802 Numbers",
    registries: ieee_802_numbers::REGISTRIES,
}];
