// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 5;
#[doc = "Dynamic Symmetric Key Provisioning Protocol (DSKPP)"]
pub mod dskpp;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "dskpp",
    title: "Dynamic Symmetric Key Provisioning Protocol (DSKPP)",
    registries: dskpp::REGISTRIES,
}];
