// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 9;
#[doc = "Application-Layer Traffic Optimization (ALTO) Protocol"]
pub mod alto_protocol;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "alto-protocol",
    title: "Application-Layer Traffic Optimization (ALTO) Protocol",
    registries: alto_protocol::REGISTRIES,
}];
