// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 4;
#[doc = "Kerberized Internet Negotiation of Keys (KINK) Parameters"]
pub mod kink;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "kink-parameters",
    title: "Kerberized Internet Negotiation of Keys (KINK) Parameters",
    registries: kink::REGISTRIES,
}];
