// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 3;
pub const REGISTRY_COUNT: usize = 23;
#[cfg(feature = "multicast-acquisition")]
#[doc = "Multicast Acquisition"]
pub mod multicast_acquisition;
#[cfg(feature = "multicast-addresses")]
#[doc = "IPv4 Multicast Address Space"]
pub mod multicast_addresses;
#[cfg(feature = "multicast-ping")]
#[doc = "Multicast Ping Protocol Parameters"]
pub mod multicast_ping;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "multicast-acquisition")]
    crate::RegistryGroup {
        id: "multicast-acquisition",
        title: "Multicast Acquisition",
        registries: multicast_acquisition::REGISTRIES,
    },
    #[cfg(feature = "multicast-addresses")]
    crate::RegistryGroup {
        id: "multicast-addresses",
        title: "IPv4 Multicast Address Space",
        registries: multicast_addresses::REGISTRIES,
    },
    #[cfg(feature = "multicast-ping")]
    crate::RegistryGroup {
        id: "multicast-ping",
        title: "Multicast Ping Protocol Parameters",
        registries: multicast_ping::REGISTRIES,
    },
];
