// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 2;
pub const REGISTRY_COUNT: usize = 5;
#[cfg(feature = "pt-eap")]
#[doc = "PT-EAP: Posture Transport (PT) Protocol For EAP Tunnel Methods"]
pub mod pt_eap;
#[cfg(feature = "pt-tls-parameters")]
#[doc = "TLS-based Posture Transport Protocol (PT-TLS)"]
pub mod pt_tls;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "pt-eap")]
    crate::RegistryGroup {
        id: "pt-eap",
        title: "PT-EAP: Posture Transport (PT) Protocol For EAP Tunnel Methods",
        registries: pt_eap::REGISTRIES,
    },
    #[cfg(feature = "pt-tls-parameters")]
    crate::RegistryGroup {
        id: "pt-tls-parameters",
        title: "TLS-based Posture Transport Protocol (PT-TLS)",
        registries: pt_tls::REGISTRIES,
    },
];
