// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 8;
pub const REGISTRY_COUNT: usize = 20;
#[cfg(feature = "imap-annotate-extension")]
#[doc = "Internet Message Access Protocol (IMAP) ANNOTATE Extension"]
pub mod imap_annotate_extension;
#[cfg(feature = "imap-capabilities")]
#[doc = "Internet Message Access Protocol (IMAP) Capabilities Registry"]
pub mod imap_capabilities;
#[cfg(feature = "imap-jmap-keywords")]
#[doc = "IMAP and JMAP Keywords"]
pub mod imap_jmap_keywords;
#[cfg(feature = "imap-list-extended")]
#[doc = "Internet Message Access Protocol (IMAP) LIST EXTENDED Registry"]
pub mod imap_list_extended;
#[cfg(feature = "imap-mailbox-name-attributes")]
#[doc = "IMAP Mailbox Name Attributes"]
pub mod imap_mailbox_name_attributes;
#[cfg(feature = "imap-metadata")]
#[doc = "IMAP METADATA Entry Registrations"]
pub mod imap_metadata;
#[cfg(feature = "imap-response-codes")]
#[doc = "IMAP Response Codes"]
pub mod imap_response_codes;
#[cfg(feature = "imap-threading-algorithms")]
#[doc = "Internet Message Access Protocol (IMAP) Threading Algorithms"]
pub mod imap_threading_algorithms;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "imap-annotate-extension")]
    crate::RegistryGroup {
        id: "imap-annotate-extension",
        title: "Internet Message Access Protocol (IMAP) ANNOTATE Extension",
        registries: imap_annotate_extension::REGISTRIES,
    },
    #[cfg(feature = "imap-capabilities")]
    crate::RegistryGroup {
        id: "imap-capabilities",
        title: "Internet Message Access Protocol (IMAP) Capabilities Registry",
        registries: imap_capabilities::REGISTRIES,
    },
    #[cfg(feature = "imap-jmap-keywords")]
    crate::RegistryGroup {
        id: "imap-jmap-keywords",
        title: "IMAP and JMAP Keywords",
        registries: imap_jmap_keywords::REGISTRIES,
    },
    #[cfg(feature = "imap-list-extended")]
    crate::RegistryGroup {
        id: "imap-list-extended",
        title: "Internet Message Access Protocol (IMAP) LIST EXTENDED Registry",
        registries: imap_list_extended::REGISTRIES,
    },
    #[cfg(feature = "imap-mailbox-name-attributes")]
    crate::RegistryGroup {
        id: "imap-mailbox-name-attributes",
        title: "IMAP Mailbox Name Attributes",
        registries: imap_mailbox_name_attributes::REGISTRIES,
    },
    #[cfg(feature = "imap-metadata")]
    crate::RegistryGroup {
        id: "imap-metadata",
        title: "IMAP METADATA Entry Registrations",
        registries: imap_metadata::REGISTRIES,
    },
    #[cfg(feature = "imap-response-codes")]
    crate::RegistryGroup {
        id: "imap-response-codes",
        title: "IMAP Response Codes",
        registries: imap_response_codes::REGISTRIES,
    },
    #[cfg(feature = "imap-threading-algorithms")]
    crate::RegistryGroup {
        id: "imap-threading-algorithms",
        title: "Internet Message Access Protocol (IMAP) Threading Algorithms",
        registries: imap_threading_algorithms::REGISTRIES,
    },
];
