// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 3;
#[doc = "Data Structure for the Security Suitability of Cryptographic Algorithms (DSSC)"]
pub mod dssc;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "dssc",
    title: "Data Structure for the Security Suitability of Cryptographic Algorithms (DSSC)",
    registries: dssc::REGISTRIES,
}];
