// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 3;
pub const REGISTRY_COUNT: usize = 5;
#[cfg(feature = "service-codes")]
#[doc = "Service Codes"]
pub mod service_codes;
#[cfg(feature = "service-function-chaining-service-function-types")]
#[doc = "Service Function Chaining Service Function Types"]
pub mod service_function_chaining_service_function_types;
#[cfg(feature = "service-names-port-numbers")]
#[doc = "Service Name and Transport Protocol Port Number Registry"]
pub mod service_names_port_numbers;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "service-codes")]
    crate::RegistryGroup {
        id: "service-codes",
        title: "Service Codes",
        registries: service_codes::REGISTRIES,
    },
    #[cfg(feature = "service-function-chaining-service-function-types")]
    crate::RegistryGroup {
        id: "service-function-chaining-service-function-types",
        title: "Service Function Chaining Service Function Types",
        registries: service_function_chaining_service_function_types::REGISTRIES,
    },
    #[cfg(feature = "service-names-port-numbers")]
    crate::RegistryGroup {
        id: "service-names-port-numbers",
        title: "Service Name and Transport Protocol Port Number Registry",
        registries: service_names_port_numbers::REGISTRIES,
    },
];
