// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 17;
#[doc = "Real-Time Transport Protocol (RTP) Parameters"]
pub mod rtp;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "rtp-parameters",
    title: "Real-Time Transport Protocol (RTP) Parameters",
    registries: rtp::REGISTRIES,
}];
