// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 3;
pub const REGISTRY_COUNT: usize = 9;
#[cfg(feature = "message-header-types")]
#[doc = "Context labels for Internet Messages"]
pub mod message_header_types;
#[cfg(feature = "message-headers")]
#[doc = "Message Headers"]
pub mod message_headers;
#[cfg(feature = "message-store-events")]
#[doc = "Internet Message Store Events"]
pub mod message_store_events;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "message-header-types")]
    crate::RegistryGroup {
        id: "message-header-types",
        title: "Context labels for Internet Messages",
        registries: message_header_types::REGISTRIES,
    },
    #[cfg(feature = "message-headers")]
    crate::RegistryGroup {
        id: "message-headers",
        title: "Message Headers",
        registries: message_headers::REGISTRIES,
    },
    #[cfg(feature = "message-store-events")]
    crate::RegistryGroup {
        id: "message-store-events",
        title: "Internet Message Store Events",
        registries: message_store_events::REGISTRIES,
    },
];
