// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 9;
#[doc = "Simple Two-way Active Measurement Protocol (STAMP) TLV Types"]
pub mod stamp_tlv_types;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "stamp-tlv-types",
    title: "Simple Two-way Active Measurement Protocol (STAMP) TLV Types",
    registries: stamp_tlv_types::REGISTRIES,
}];
