// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 7;
#[doc = "IPv6 Low Power Personal Area Network Parameters"]
pub mod v6lowpan;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "_6lowpan-parameters",
    title: "IPv6 Low Power Personal Area Network Parameters",
    registries: v6lowpan::REGISTRIES,
}];
