// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 4;
#[doc = "Portable Symmetric Key Container (PSKC)"]
pub mod pskc;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "pskc",
    title: "Portable Symmetric Key Container (PSKC)",
    registries: pskc::REGISTRIES,
}];
