// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 4;
#[doc = "XMSS: Extended Hash-Based Signatures"]
pub mod xmss_extended_hash_based_signatures;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "xmss-extended-hash-based-signatures",
    title: "XMSS: Extended Hash-Based Signatures",
    registries: xmss_extended_hash_based_signatures::REGISTRIES,
}];
