// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 13;
#[doc = "Content-Centric Networking (CCNx)"]
pub mod ccnx;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "ccnx",
    title: "Content-Centric Networking (CCNx)",
    registries: ccnx::REGISTRIES,
}];
