// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 3;
#[doc = "Connectivity Fault Management (CFM) OAM IETF Parameters"]
pub mod cfm_oam;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "cfm-oam",
    title: "Connectivity Fault Management (CFM) OAM IETF Parameters",
    registries: cfm_oam::REGISTRIES,
}];
