// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 3;
pub const REGISTRY_COUNT: usize = 8;
#[cfg(feature = "sieve-environment-items")]
#[doc = "Sieve Environment Items"]
pub mod sieve_environment_items;
#[cfg(feature = "sieve-extensions")]
#[doc = "Sieve Extensions"]
pub mod sieve_extensions;
#[cfg(feature = "sieve-notification")]
#[doc = "Sieve Notification Mechanisms"]
pub mod sieve_notification;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "sieve-environment-items")]
    crate::RegistryGroup {
        id: "sieve-environment-items",
        title: "Sieve Environment Items",
        registries: sieve_environment_items::REGISTRIES,
    },
    #[cfg(feature = "sieve-extensions")]
    crate::RegistryGroup {
        id: "sieve-extensions",
        title: "Sieve Extensions",
        registries: sieve_extensions::REGISTRIES,
    },
    #[cfg(feature = "sieve-notification")]
    crate::RegistryGroup {
        id: "sieve-notification",
        title: "Sieve Notification Mechanisms",
        registries: sieve_notification::REGISTRIES,
    },
];
