// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 2;
pub const REGISTRY_COUNT: usize = 14;
#[cfg(feature = "ioam")]
#[doc = "In Situ OAM (IOAM)"]
pub mod ioam;
#[cfg(feature = "ioam-capabilities")]
#[doc = "In Situ OAM (IOAM) Capabilities"]
pub mod ioam_capabilities;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "ioam")]
    crate::RegistryGroup {
        id: "ioam",
        title: "In Situ OAM (IOAM)",
        registries: ioam::REGISTRIES,
    },
    #[cfg(feature = "ioam-capabilities")]
    crate::RegistryGroup {
        id: "ioam-capabilities",
        title: "In Situ OAM (IOAM) Capabilities",
        registries: ioam_capabilities::REGISTRIES,
    },
];
