// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 27;
#[doc = "Group Domain of Interpretation (GDOI) Payloads"]
pub mod gdoi_payloads;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "gdoi-payloads",
    title: "Group Domain of Interpretation (GDOI) Payloads",
    registries: gdoi_payloads::REGISTRIES,
}];
