// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 6;
#[doc = "Dynamic Host Configuration Protocol (DHCP) Authentication Option Name Spaces"]
pub mod auth_namespaces;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "auth-namespaces",
    title: "Dynamic Host Configuration Protocol (DHCP) Authentication Option Name Spaces",
    registries: auth_namespaces::REGISTRIES,
}];
