// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 4;
#[doc = "Peer-to-Peer Streaming Tracker Protocol (PPSTP)"]
pub mod ppsp_tp;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "ppsp-tp",
    title: "Peer-to-Peer Streaming Tracker Protocol (PPSTP)",
    registries: ppsp_tp::REGISTRIES,
}];
