// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "VCDIFF Secondary Compressor ID Values"]
pub mod vcdiff_comp_ids;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "vcdiff-comp-ids",
    title: "VCDIFF Secondary Compressor ID Values",
    registries: vcdiff_comp_ids::REGISTRIES,
}];
