// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 5;
#[doc = "Posture Broker (PB) Protocol Compatible with Trusted Network Connect (TNC) Parameters"]
pub mod pb_tnc;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "pb-tnc-parameters",
    title: "Posture Broker (PB) Protocol Compatible with Trusted Network Connect (TNC) Parameters",
    registries: pb_tnc::REGISTRIES,
}];
