// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 48;
#[doc = "Internet Control Message Protocol (ICMP) Parameters"]
pub mod icmp;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "icmp-parameters",
    title: "Internet Control Message Protocol (ICMP) Parameters",
    registries: icmp::REGISTRIES,
}];
