// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "ONC RPC Universal Address (uaddr) Format Registry"]
pub mod uaddr_formats;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "uaddr-formats",
    title: "ONC RPC Universal Address (uaddr) Format Registry",
    registries: uaddr_formats::REGISTRIES,
}];
