// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 2;
pub const REGISTRY_COUNT: usize = 5;
#[cfg(feature = "mgcp-localconnectionoptions")]
#[doc = "Media Gateway Control Protocol (MGCP)"]
pub mod mgcp_localconnectionoptions;
#[cfg(feature = "mgcp-packages")]
#[doc = "Media Gateway Control Protocol (MGCP) Package Registry"]
pub mod mgcp_packages;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "mgcp-localconnectionoptions")]
    crate::RegistryGroup {
        id: "mgcp-localconnectionoptions",
        title: "Media Gateway Control Protocol (MGCP)",
        registries: mgcp_localconnectionoptions::REGISTRIES,
    },
    #[cfg(feature = "mgcp-packages")]
    crate::RegistryGroup {
        id: "mgcp-packages",
        title: "Media Gateway Control Protocol (MGCP) Package Registry",
        registries: mgcp_packages::REGISTRIES,
    },
];
