// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 3;
#[doc = "Distributed Node Consensus Protocol (DNCP)"]
pub mod dncp_registry;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "dncp-registry",
    title: "Distributed Node Consensus Protocol (DNCP)",
    registries: dncp_registry::REGISTRIES,
}];
