// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 5;
pub const REGISTRY_COUNT: usize = 44;
#[cfg(feature = "mpls-id-type")]
#[doc = "Multiprotocol Label Switching Architecture (MPLS) Identifier Types"]
pub mod mpls_id_type;
#[cfg(feature = "mpls-label-values")]
#[doc = "Special-Purpose Multiprotocol Label Switching (MPLS) Label Values"]
pub mod mpls_label_values;
#[cfg(feature = "mpls-lsp-ping-parameters")]
#[doc = "Multiprotocol Label Switching (MPLS) Label Switched Paths (LSPs) Ping Parameters"]
pub mod mpls_lsp_ping;
#[cfg(feature = "mpls-multi-topology-parameters")]
#[doc = "MPLS Multi-Topology Identifiers"]
pub mod mpls_multi_topology;
#[cfg(feature = "mpls-network-actions")]
#[doc = "MPLS Network Actions"]
pub mod mpls_network_actions;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "mpls-id-type")]
    crate::RegistryGroup {
        id: "mpls-id-type",
        title: "Multiprotocol Label Switching Architecture (MPLS) Identifier Types",
        registries: mpls_id_type::REGISTRIES,
    },
    #[cfg(feature = "mpls-label-values")]
    crate::RegistryGroup {
        id: "mpls-label-values",
        title: "Special-Purpose Multiprotocol Label Switching (MPLS) Label Values",
        registries: mpls_label_values::REGISTRIES,
    },
    #[cfg(feature = "mpls-lsp-ping-parameters")]
    crate::RegistryGroup {
        id: "mpls-lsp-ping-parameters",
        title: "Multiprotocol Label Switching (MPLS) Label Switched Paths (LSPs) Ping Parameters",
        registries: mpls_lsp_ping::REGISTRIES,
    },
    #[cfg(feature = "mpls-multi-topology-parameters")]
    crate::RegistryGroup {
        id: "mpls-multi-topology-parameters",
        title: "MPLS Multi-Topology Identifiers",
        registries: mpls_multi_topology::REGISTRIES,
    },
    #[cfg(feature = "mpls-network-actions")]
    crate::RegistryGroup {
        id: "mpls-network-actions",
        title: "MPLS Network Actions",
        registries: mpls_network_actions::REGISTRIES,
    },
];
