// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 12;
#[doc = "Internet Open Trading Protocol (IOTP) Codes"]
pub mod iotp_codes;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "iotp-codes",
    title: "Internet Open Trading Protocol (IOTP) Codes",
    registries: iotp_codes::REGISTRIES,
}];
