// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "Cryptographic Suites for IKEv1, IKEv2, and IPsec"]
pub mod crypto_suites;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "crypto-suites",
    title: "Cryptographic Suites for IKEv1, IKEv2, and IPsec",
    registries: crypto_suites::REGISTRIES,
}];
