// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 3;
pub const REGISTRY_COUNT: usize = 9;
#[cfg(feature = "rpc-authentication-numbers")]
#[doc = "Remote Procedure Call (RPC) Authentication Numbers"]
pub mod rpc_authentication_numbers;
#[cfg(feature = "rpc-netids")]
#[doc = "ONC RPC Network Identifiers (netids)"]
pub mod rpc_netids;
#[cfg(feature = "rpc-program-numbers")]
#[doc = "Remote Procedure Call (RPC) Program Numbers"]
pub mod rpc_program_numbers;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "rpc-authentication-numbers")]
    crate::RegistryGroup {
        id: "rpc-authentication-numbers",
        title: "Remote Procedure Call (RPC) Authentication Numbers",
        registries: rpc_authentication_numbers::REGISTRIES,
    },
    #[cfg(feature = "rpc-netids")]
    crate::RegistryGroup {
        id: "rpc-netids",
        title: "ONC RPC Network Identifiers (netids)",
        registries: rpc_netids::REGISTRIES,
    },
    #[cfg(feature = "rpc-program-numbers")]
    crate::RegistryGroup {
        id: "rpc-program-numbers",
        title: "Remote Procedure Call (RPC) Program Numbers",
        registries: rpc_program_numbers::REGISTRIES,
    },
];
