// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 128;
#[doc = "Structure of Management Information (SMI) Numbers (MIB Module Registrations)"]
pub mod smi_numbers;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "smi-numbers",
    title: "Structure of Management Information (SMI) Numbers (MIB Module Registrations)",
    registries: smi_numbers::REGISTRIES,
}];
