// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 2;
pub const REGISTRY_COUNT: usize = 4;
#[cfg(feature = "ipv4-address-space")]
#[doc = "IPv4 Address Space"]
pub mod ipv4_address_space;
#[cfg(feature = "ipv4-recovered-address-space")]
#[doc = "IPv4 Recovered Address Space"]
pub mod ipv4_recovered_address_space;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "ipv4-address-space")]
    crate::RegistryGroup {
        id: "ipv4-address-space",
        title: "IPv4 Address Space",
        registries: ipv4_address_space::REGISTRIES,
    },
    #[cfg(feature = "ipv4-recovered-address-space")]
    crate::RegistryGroup {
        id: "ipv4-recovered-address-space",
        title: "IPv4 Recovered Address Space",
        registries: ipv4_recovered_address_space::REGISTRIES,
    },
];
