// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 4;
pub const REGISTRY_COUNT: usize = 11;
#[cfg(feature = "yang-parameters")]
#[doc = "YANG Parameters"]
pub mod yang;
#[cfg(feature = "yang-geographic-location")]
#[doc = "YANG Geographic Location Parameters"]
pub mod yang_geographic_location;
#[cfg(feature = "yang-module-tags")]
#[doc = "YANG Module Tags"]
pub mod yang_module_tags;
#[cfg(feature = "yang-sid")]
#[doc = "YANG SIDs"]
pub mod yang_sid;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "yang-geographic-location")]
    crate::RegistryGroup {
        id: "yang-geographic-location",
        title: "YANG Geographic Location Parameters",
        registries: yang_geographic_location::REGISTRIES,
    },
    #[cfg(feature = "yang-module-tags")]
    crate::RegistryGroup {
        id: "yang-module-tags",
        title: "YANG Module Tags",
        registries: yang_module_tags::REGISTRIES,
    },
    #[cfg(feature = "yang-parameters")]
    crate::RegistryGroup {
        id: "yang-parameters",
        title: "YANG Parameters",
        registries: yang::REGISTRIES,
    },
    #[cfg(feature = "yang-sid")]
    crate::RegistryGroup {
        id: "yang-sid",
        title: "YANG SIDs",
        registries: yang_sid::REGISTRIES,
    },
];
