// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 2;
pub const REGISTRY_COUNT: usize = 19;
#[cfg(feature = "ospfv3-parameters")]
#[doc = "Open Shortest Path First v3 (OSPFv3) Parameters"]
pub mod ospfv3;
#[cfg(feature = "ospfv3-authentication-trailer-options")]
#[doc = "Open Shortest Path First v3 (OSPFv3) Authentication Trailer Options"]
pub mod ospfv3_authentication_trailer_options;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "ospfv3-authentication-trailer-options")]
    crate::RegistryGroup {
        id: "ospfv3-authentication-trailer-options",
        title: "Open Shortest Path First v3 (OSPFv3) Authentication Trailer Options",
        registries: ospfv3_authentication_trailer_options::REGISTRIES,
    },
    #[cfg(feature = "ospfv3-parameters")]
    crate::RegistryGroup {
        id: "ospfv3-parameters",
        title: "Open Shortest Path First v3 (OSPFv3) Parameters",
        registries: ospfv3::REGISTRIES,
    },
];
