// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 5;
#[doc = "Uniform Resource Identifier (URI) Schemes"]
pub mod uri_schemes;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "uri-schemes",
    title: "Uniform Resource Identifier (URI) Schemes",
    registries: uri_schemes::REGISTRIES,
}];
