// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 14;
#[doc = "Multicast Address-Set Claim (MASC) Parameters"]
pub mod masc;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "masc-parameters",
    title: "Multicast Address-Set Claim (MASC) Parameters",
    registries: masc::REGISTRIES,
}];
