// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 9;
#[doc = "Common Name Resolution Protocol (CNRP) Parameters"]
pub mod cnrp;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "cnrp-parameters",
    title: "Common Name Resolution Protocol (CNRP) Parameters",
    registries: cnrp::REGISTRIES,
}];
