// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 2;
pub const REGISTRY_COUNT: usize = 5;
#[cfg(feature = "s-naptr-parameters")]
#[doc = "Straightforward-NAPTR (S-NAPTR) Parameters"]
pub mod s_naptr;
#[cfg(feature = "s-pmsi-parameters")]
#[doc = "Selective P-Multicast Service Interface (S-PMSI) Parameters"]
pub mod s_pmsi;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "s-naptr-parameters")]
    crate::RegistryGroup {
        id: "s-naptr-parameters",
        title: "Straightforward-NAPTR (S-NAPTR) Parameters",
        registries: s_naptr::REGISTRIES,
    },
    #[cfg(feature = "s-pmsi-parameters")]
    crate::RegistryGroup {
        id: "s-pmsi-parameters",
        title: "Selective P-Multicast Service Interface (S-PMSI) Parameters",
        registries: s_pmsi::REGISTRIES,
    },
];
