// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 3;
#[doc = "Uniform Resource Name (URN) Namespace for IETF Use"]
pub mod params;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "params",
    title: "Uniform Resource Name (URN) Namespace for IETF Use",
    registries: params::REGISTRIES,
}];
