// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "Permanent IPv6 Multicast Group Identifiers"]
pub mod perm_mcast_groupids;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "perm-mcast-groupids",
    title: "Permanent IPv6 Multicast Group Identifiers",
    registries: perm_mcast_groupids::REGISTRIES,
}];
