// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 16;
#[doc = "Content Delivery Network Interconnection (CDNI) Parameters"]
pub mod cdni;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "cdni-parameters",
    title: "Content Delivery Network Interconnection (CDNI) Parameters",
    registries: cdni::REGISTRIES,
}];
