// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 12;
#[doc = "Software Update for the Internet of Things (SUIT)"]
pub mod suit;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "suit",
    title: "Software Update for the Internet of Things (SUIT)",
    registries: suit::REGISTRIES,
}];
