// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 11;
pub const REGISTRY_COUNT: usize = 77;
#[cfg(feature = "eap-channel-binding-parameters")]
#[doc = "Extensible Authentication Protocol (EAP) Channel-Binding Parameters"]
pub mod eap_channel_binding;
#[cfg(feature = "eap-eke")]
#[doc = "Extensible Authentication Protocol (EAP) Encrypted Key Exchange (EKE) Registry"]
pub mod eap_eke;
#[cfg(feature = "eap-fast-parameters")]
#[doc = "Flexible Authentication via Secure Tunneling Extensible Authentication Protocol (EAP-FAST) Parameters"]
pub mod eap_fast;
#[cfg(feature = "eap-gpsk-parameters")]
#[doc = "Extensible Authentication Protocol Generalized Pre-Shared Key (EAP-GPSK) Parameters"]
pub mod eap_gpsk;
#[cfg(feature = "eap-ikev2-payloads")]
#[doc = "Extensible Authentication Protocol-Internet Key Exchange Version 2 (EAP-IKEv2) Payloads"]
pub mod eap_ikev2_payloads;
#[cfg(feature = "eap-noob")]
#[doc = "Nimble Out-of-Band Authentication for EAP Parameters (EAP-NOOB)"]
pub mod eap_noob;
#[cfg(feature = "eap-numbers")]
#[doc = "Extensible Authentication Protocol (EAP) Registry"]
pub mod eap_numbers;
#[cfg(feature = "eap-pax")]
#[doc = "Extensible Authentication Protocol - Password Authenticated Exchange (EAP-PAX)"]
pub mod eap_pax;
#[cfg(feature = "eap-psk-parameters")]
#[doc = "Extensible Authentication Protocol (EAP) EXT_Type Parameters"]
pub mod eap_psk;
#[cfg(feature = "eap-pwd-parameters")]
#[doc = "EAP-pwd Parameters"]
pub mod eap_pwd;
#[cfg(feature = "eap-sake-parameters")]
#[doc = "Extensible Authentication Protocol Method for Shared-secret Authentication and Key Establishment (EAP-SAKE)"]
pub mod eap_sake;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "eap-channel-binding-parameters")]
    crate::RegistryGroup {
        id: "eap-channel-binding-parameters",
        title: "Extensible Authentication Protocol (EAP) Channel-Binding Parameters",
        registries: eap_channel_binding::REGISTRIES,
    },
    #[cfg(feature = "eap-eke")]
    crate::RegistryGroup {
        id: "eap-eke",
        title: "Extensible Authentication Protocol (EAP) Encrypted Key Exchange (EKE) Registry",
        registries: eap_eke::REGISTRIES,
    },
    #[cfg(feature = "eap-fast-parameters")]
    crate::RegistryGroup {
        id: "eap-fast-parameters",
        title: "Flexible Authentication via Secure Tunneling Extensible Authentication Protocol (EAP-FAST) Parameters",
        registries: eap_fast::REGISTRIES,
    },
    #[cfg(feature = "eap-gpsk-parameters")]
    crate::RegistryGroup {
        id: "eap-gpsk-parameters",
        title: "Extensible Authentication Protocol Generalized Pre-Shared Key (EAP-GPSK) Parameters",
        registries: eap_gpsk::REGISTRIES,
    },
    #[cfg(feature = "eap-ikev2-payloads")]
    crate::RegistryGroup {
        id: "eap-ikev2-payloads",
        title: "Extensible Authentication Protocol-Internet Key Exchange Version 2 (EAP-IKEv2) Payloads",
        registries: eap_ikev2_payloads::REGISTRIES,
    },
    #[cfg(feature = "eap-noob")]
    crate::RegistryGroup {
        id: "eap-noob",
        title: "Nimble Out-of-Band Authentication for EAP Parameters (EAP-NOOB)",
        registries: eap_noob::REGISTRIES,
    },
    #[cfg(feature = "eap-numbers")]
    crate::RegistryGroup {
        id: "eap-numbers",
        title: "Extensible Authentication Protocol (EAP) Registry",
        registries: eap_numbers::REGISTRIES,
    },
    #[cfg(feature = "eap-pax")]
    crate::RegistryGroup {
        id: "eap-pax",
        title: "Extensible Authentication Protocol - Password Authenticated Exchange (EAP-PAX)",
        registries: eap_pax::REGISTRIES,
    },
    #[cfg(feature = "eap-psk-parameters")]
    crate::RegistryGroup {
        id: "eap-psk-parameters",
        title: "Extensible Authentication Protocol (EAP) EXT_Type Parameters",
        registries: eap_psk::REGISTRIES,
    },
    #[cfg(feature = "eap-pwd-parameters")]
    crate::RegistryGroup {
        id: "eap-pwd-parameters",
        title: "EAP-pwd Parameters",
        registries: eap_pwd::REGISTRIES,
    },
    #[cfg(feature = "eap-sake-parameters")]
    crate::RegistryGroup {
        id: "eap-sake-parameters",
        title: "Extensible Authentication Protocol Method for Shared-secret Authentication and Key Establishment (EAP-SAKE)",
        registries: eap_sake::REGISTRIES,
    },
];
