// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 7;
#[doc = "Routing Information Protocol (RIP) Parameters"]
pub mod rip_types;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "rip-types",
    title: "Routing Information Protocol (RIP) Parameters",
    registries: rip_types::REGISTRIES,
}];
