// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 3;
pub const REGISTRY_COUNT: usize = 9;
#[cfg(feature = "xml-ns-provided-by")]
#[doc = "US National Emergency Number Administration (NENA) Provided-By Schema"]
pub mod xml_ns_provided_by;
#[cfg(feature = "xml-registry")]
#[doc = "IETF XML Registry"]
pub mod xml_registry;
#[cfg(feature = "xml-security-uris")]
#[doc = "XML Security URIs"]
pub mod xml_security_uris;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "xml-ns-provided-by")]
    crate::RegistryGroup {
        id: "xml-ns-provided-by",
        title: "US National Emergency Number Administration (NENA) Provided-By Schema",
        registries: xml_ns_provided_by::REGISTRIES,
    },
    #[cfg(feature = "xml-registry")]
    crate::RegistryGroup {
        id: "xml-registry",
        title: "IETF XML Registry",
        registries: xml_registry::REGISTRIES,
    },
    #[cfg(feature = "xml-security-uris")]
    crate::RegistryGroup {
        id: "xml-security-uris",
        title: "XML Security URIs",
        registries: xml_security_uris::REGISTRIES,
    },
];
