// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 3;
pub const REGISTRY_COUNT: usize = 12;
#[cfg(feature = "ip-parameters")]
#[doc = "Internet Protocol Version 4 (IPv4) Parameters"]
pub mod ip;
#[cfg(feature = "ip-over-IEEE1394")]
#[doc = "Namespaces for IP over IEEE 1394"]
pub mod ip_over_ieee1394;
#[cfg(feature = "ip-xns-mapping")]
#[doc = "Internet - Xerox Network System (XNS) Protocol Mappings"]
pub mod ip_xns_mapping;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "ip-over-IEEE1394")]
    crate::RegistryGroup {
        id: "ip-over-IEEE1394",
        title: "Namespaces for IP over IEEE 1394",
        registries: ip_over_ieee1394::REGISTRIES,
    },
    #[cfg(feature = "ip-parameters")]
    crate::RegistryGroup {
        id: "ip-parameters",
        title: "Internet Protocol Version 4 (IPv4) Parameters",
        registries: ip::REGISTRIES,
    },
    #[cfg(feature = "ip-xns-mapping")]
    crate::RegistryGroup {
        id: "ip-xns-mapping",
        title: "Internet - Xerox Network System (XNS) Protocol Mappings",
        registries: ip_xns_mapping::REGISTRIES,
    },
];
