// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 16;
#[doc = "Probabilistic Routing Protocol using History of Encounters and Transitivity (PRoPHET)"]
pub mod prophet;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "prophet",
    title: "Probabilistic Routing Protocol using History of Encounters and Transitivity (PRoPHET)",
    registries: prophet::REGISTRIES,
}];
