// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 3;
#[doc = "Leighton-Micali Signatures (LMS)"]
pub mod leighton_micali_signatures;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "leighton-micali-signatures",
    title: "Leighton-Micali Signatures (LMS)",
    registries: leighton_micali_signatures::REGISTRIES,
}];
