// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "Transport Layer Security (TLS) Compression Method Identifiers"]
pub mod comp_meth_ids;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "comp-meth-ids",
    title: "Transport Layer Security (TLS) Compression Method Identifiers",
    registries: comp_meth_ids::REGISTRIES,
}];
