// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 31;
#[doc = "Internet Key Exchange Version 2 (IKEv2) Parameters"]
pub mod ikev2;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "ikev2-parameters",
    title: "Internet Key Exchange Version 2 (IKEv2) Parameters",
    registries: ikev2::REGISTRIES,
}];
