// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "Tunnel Setup Protocol (TSP) Parameters"]
pub mod tunnel_setup_protocol;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "tunnel-setup-protocol",
    title: "Tunnel Setup Protocol (TSP) Parameters",
    registries: tunnel_setup_protocol::REGISTRIES,
}];
