// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "Remote Direct Data Placement"]
pub mod remote_direct_data_placement;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "remote-direct-data-placement",
    title: "Remote Direct Data Placement",
    registries: remote_direct_data_placement::REGISTRIES,
}];
