// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 2;
pub const REGISTRY_COUNT: usize = 4;
#[cfg(feature = "authentication-cryptographic-protocol-id")]
#[doc = "Keying and Authentication for Routing Protocols (KARP) Parameters"]
pub mod authentication_cryptographic_protocol_id;
#[cfg(feature = "authentication-method-reference-values")]
#[doc = "Authentication Method Reference Values"]
pub mod authentication_method_reference_values;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "authentication-cryptographic-protocol-id")]
    crate::RegistryGroup {
        id: "authentication-cryptographic-protocol-id",
        title: "Keying and Authentication for Routing Protocols (KARP) Parameters",
        registries: authentication_cryptographic_protocol_id::REGISTRIES,
    },
    #[cfg(feature = "authentication-method-reference-values")]
    crate::RegistryGroup {
        id: "authentication-method-reference-values",
        title: "Authentication Method Reference Values",
        registries: authentication_method_reference_values::REGISTRIES,
    },
];
