// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 4;
#[doc = "Negative-ACKnowledgment (NACK) Oriented Reliable Multicast (NORM) Parameters"]
pub mod norm;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "norm-parameters",
    title: "Negative-ACKnowledgment (NACK) Oriented Reliable Multicast (NORM) Parameters",
    registries: norm::REGISTRIES,
}];
