// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "Multicast Source Discovery Protocol (MSDP) TLV Values Registry"]
pub mod msdp_tlv_values;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "msdp-tlv-values",
    title: "Multicast Source Discovery Protocol (MSDP) TLV Values Registry",
    registries: msdp_tlv_values::REGISTRIES,
}];
