// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 3;
#[doc = "Dynamic Source Routing (DSR) Protocol Parameters"]
pub mod dsr;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "dsr-parameters",
    title: "Dynamic Source Routing (DSR) Protocol Parameters",
    registries: dsr::REGISTRIES,
}];
