// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 2;
pub const REGISTRY_COUNT: usize = 8;
#[cfg(feature = "urn-namespaces")]
#[doc = "Uniform Resource Names (URN) Namespaces"]
pub mod urn_namespaces;
#[cfg(feature = "urn-serviceid-labels")]
#[doc = "Service URN Labels"]
pub mod urn_serviceid_labels;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "urn-namespaces")]
    crate::RegistryGroup {
        id: "urn-namespaces",
        title: "Uniform Resource Names (URN) Namespaces",
        registries: urn_namespaces::REGISTRIES,
    },
    #[cfg(feature = "urn-serviceid-labels")]
    crate::RegistryGroup {
        id: "urn-serviceid-labels",
        title: "Service URN Labels",
        registries: urn_serviceid_labels::REGISTRIES,
    },
];
