// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 3;
#[doc = "Two-way Active Measurement Protocol (TWAMP) Parameters"]
pub mod twamp;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "twamp-parameters",
    title: "Two-way Active Measurement Protocol (TWAMP) Parameters",
    registries: twamp::REGISTRIES,
}];
