// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
//! Type-safe, allocation-free bindings to IANA protocol registries.
#![no_std]
#[cfg(feature = "metadata")]
pub use iana::{Record, Registry, RegistryGroup};
pub use iana::{RegistryInfo, Status};
mod generated;
pub use generated::*;
