// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "Server Cache Synchronization Protocol (SCSP) Parameters"]
pub mod scsp_numbers;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "scsp-numbers",
    title: "Server Cache Synchronization Protocol (SCSP) Parameters",
    registries: scsp_numbers::REGISTRIES,
}];
