// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "Mail Encoding Header Field Keywords"]
pub mod mail_encoding;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "mail-encoding",
    title: "Mail Encoding Header Field Keywords",
    registries: mail_encoding::REGISTRIES,
}];
