// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "Experimental Mobility Protocol Subtype Registry"]
pub mod ex_mobility_subtypes;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "ex-mobility-subtypes",
    title: "Experimental Mobility Protocol Subtype Registry",
    registries: ex_mobility_subtypes::REGISTRIES,
}];
