// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 39;
#[doc = "Layer Two Tunneling Protocol \"L2TP\""]
pub mod l2tp;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "l2tp-parameters",
    title: "Layer Two Tunneling Protocol \"L2TP\"",
    registries: l2tp::REGISTRIES,
}];
