// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 2;
pub const REGISTRY_COUNT: usize = 4;
#[cfg(feature = "security-label-format-selection")]
#[doc = "Security Label Format Selection"]
pub mod security_label_format_selection;
#[cfg(feature = "security-txt-fields")]
#[doc = "security.txt Fields"]
pub mod security_txt_fields;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "security-label-format-selection")]
    crate::RegistryGroup {
        id: "security-label-format-selection",
        title: "Security Label Format Selection",
        registries: security_label_format_selection::REGISTRIES,
    },
    #[cfg(feature = "security-txt-fields")]
    crate::RegistryGroup {
        id: "security-txt-fields",
        title: "security.txt Fields",
        registries: security_txt_fields::REGISTRIES,
    },
];
