// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 10;
#[doc = "IPv6 Over the TSCH Mode of IEEE 802.15.4 (6TiSCH)"]
pub mod v6tisch;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "_6tisch",
    title: "IPv6 Over the TSCH Mode of IEEE 802.15.4 (6TiSCH)",
    registries: v6tisch::REGISTRIES,
}];
