// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 12;
#[doc = "QoS NSIS Signal Layering Protocol (NSLP) QSPEC Parameters"]
pub mod qspec;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "qspec",
    title: "QoS NSIS Signal Layering Protocol (NSLP) QSPEC Parameters",
    registries: qspec::REGISTRIES,
}];
