// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 2;
pub const REGISTRY_COUNT: usize = 36;
#[cfg(feature = "rpl")]
#[doc = "Routing Protocol for Low Power and Lossy Networks (RPL)"]
pub mod rpl;
#[cfg(feature = "rpl-routing-metric-constraint")]
#[doc = "Routing Protocol for Low Power and Lossy Networks (RPL) Routing Metric/Constraint"]
pub mod rpl_routing_metric_constraint;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "rpl")]
    crate::RegistryGroup {
        id: "rpl",
        title: "Routing Protocol for Low Power and Lossy Networks (RPL)",
        registries: rpl::REGISTRIES,
    },
    #[cfg(feature = "rpl-routing-metric-constraint")]
    crate::RegistryGroup {
        id: "rpl-routing-metric-constraint",
        title: "Routing Protocol for Low Power and Lossy Networks (RPL) Routing Metric/Constraint",
        registries: rpl_routing_metric_constraint::REGISTRIES,
    },
];
