// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 3;
#[doc = "Post Office Protocol version 3 (POP3) Extension Mechanism"]
pub mod pop3_extension_mechanism;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "pop3-extension-mechanism",
    title: "Post Office Protocol version 3 (POP3) Extension Mechanism",
    registries: pop3_extension_mechanism::REGISTRIES,
}];
