// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 3;
#[doc = "Point-to-Point Over Ethernet (PPPoE) Parameters"]
pub mod pppoe;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "pppoe-parameters",
    title: "Point-to-Point Over Ethernet (PPPoE) Parameters",
    registries: pppoe::REGISTRIES,
}];
