// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 18;
#[doc = "Signaling User Adaptation Layer Assignments"]
pub mod sigtran_adapt;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "sigtran-adapt",
    title: "Signaling User Adaptation Layer Assignments",
    registries: sigtran_adapt::REGISTRIES,
}];
