// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 2;
pub const REGISTRY_COUNT: usize = 3;
#[cfg(feature = "charset-info")]
#[doc = "Character Sets Mailing List Information"]
pub mod charset_info;
#[cfg(feature = "charset-reg")]
#[doc = "Character Set Registrations"]
pub mod charset_reg;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "charset-info")]
    crate::RegistryGroup {
        id: "charset-info",
        title: "Character Sets Mailing List Information",
        registries: charset_info::REGISTRIES,
    },
    #[cfg(feature = "charset-reg")]
    crate::RegistryGroup {
        id: "charset-reg",
        title: "Character Set Registrations",
        registries: charset_reg::REGISTRIES,
    },
];
