// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "Subsequent Address Family Identifiers (SAFI) Parameters"]
pub mod safi_namespace;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "safi-namespace",
    title: "Subsequent Address Family Identifiers (SAFI) Parameters",
    registries: safi_namespace::REGISTRIES,
}];
