// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 4;
pub const REGISTRY_COUNT: usize = 10;
#[cfg(feature = "nfsv4-device-id-notifications")]
#[doc = "NFSv4 Device ID Notifications"]
pub mod nfsv4_device_id_notifications;
#[cfg(feature = "nfsv4-named-attributes")]
#[doc = "NFSv4 Named Attribute Definitions"]
pub mod nfsv4_named_attributes;
#[cfg(feature = "nfsv4-path-variables")]
#[doc = "NFSv4 Path Variables"]
pub mod nfsv4_path_variables;
#[cfg(feature = "nfsv4-recallable-object-types")]
#[doc = "NFSv4 Recallable Object Types"]
pub mod nfsv4_recallable_object_types;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "nfsv4-device-id-notifications")]
    crate::RegistryGroup {
        id: "nfsv4-device-id-notifications",
        title: "NFSv4 Device ID Notifications",
        registries: nfsv4_device_id_notifications::REGISTRIES,
    },
    #[cfg(feature = "nfsv4-named-attributes")]
    crate::RegistryGroup {
        id: "nfsv4-named-attributes",
        title: "NFSv4 Named Attribute Definitions",
        registries: nfsv4_named_attributes::REGISTRIES,
    },
    #[cfg(feature = "nfsv4-path-variables")]
    crate::RegistryGroup {
        id: "nfsv4-path-variables",
        title: "NFSv4 Path Variables",
        registries: nfsv4_path_variables::REGISTRIES,
    },
    #[cfg(feature = "nfsv4-recallable-object-types")]
    crate::RegistryGroup {
        id: "nfsv4-recallable-object-types",
        title: "NFSv4 Recallable Object Types",
        registries: nfsv4_recallable_object_types::REGISTRIES,
    },
];
