// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 8;
#[doc = "Resource Public Key Infrastructure (RPKI)"]
pub mod rpki;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "rpki",
    title: "Resource Public Key Infrastructure (RPKI)",
    registries: rpki::REGISTRIES,
}];
