// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "Application Bridging for Federated Access Beyond Web (ABFAB) Parameters"]
pub mod abfab;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "abfab-parameters",
    title: "Application Bridging for Federated Access Beyond Web (ABFAB) Parameters",
    registries: abfab::REGISTRIES,
}];
