// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 5;
#[doc = "Application Access Protocol (ACAP) Numbers"]
pub mod acap_registrations;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "acap-registrations",
    title: "Application Access Protocol (ACAP) Numbers",
    registries: acap_registrations::REGISTRIES,
}];
