// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "Electronic Commerce Modeling Language (ECML) Parameters"]
pub mod ecml;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "ecml-parameters",
    title: "Electronic Commerce Modeling Language (ECML) Parameters",
    registries: ecml::REGISTRIES,
}];
