// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 29;
pub const REGISTRY_COUNT: usize = 32;
#[cfg(feature = "iana-as-numbers-special-registry")]
#[doc = "Special-Purpose Autonomous System (AS) Numbers"]
pub mod iana_as_numbers_special_registry;
#[cfg(feature = "iana-bfd-types")]
#[doc = "iana-bfd-types YANG Module"]
pub mod iana_bfd_types;
#[cfg(feature = "iana-bgp-l2-encaps")]
#[doc = "iana-bgp-l2-encaps YANG Module"]
pub mod iana_bgp_l2_encaps;
#[cfg(feature = "iana-crypt-hash")]
#[doc = "iana-crypt-hash YANG Module"]
pub mod iana_crypt_hash;
#[cfg(feature = "iana-dns-class-rr-type")]
#[doc = "iana-dns-class-rr-type YANG Module"]
pub mod iana_dns_class_rr_type;
#[cfg(feature = "iana-dots-signal-channel")]
#[doc = "iana-dots-signal-channel YANG Module"]
pub mod iana_dots_signal_channel;
#[cfg(feature = "iana-hardware")]
#[doc = "iana-hardware YANG Module"]
pub mod iana_hardware;
#[cfg(feature = "iana-http-versions")]
#[doc = "iana-http-versions YANG Module"]
pub mod iana_http_versions;
#[cfg(feature = "iana-icmpv4-types")]
#[doc = "iana-icmpv4-types YANG Module"]
pub mod iana_icmpv4_types;
#[cfg(feature = "iana-icmpv6-types")]
#[doc = "iana-icmpv6-types YANG Module"]
pub mod iana_icmpv6_types;
#[cfg(feature = "iana-if-type")]
#[doc = "iana-if-type YANG Module"]
pub mod iana_if_type;
#[cfg(feature = "iana-igp-algo-types")]
#[doc = "iana-igp-algo-types YANG Module"]
pub mod iana_igp_algo_types;
#[cfg(feature = "iana-igp-link-attr-apps")]
#[doc = "iana-igp-link-attr-apps YANG Module"]
pub mod iana_igp_link_attr_apps;
#[cfg(feature = "iana-igp-metric-types")]
#[doc = "iana-igp-metric-types YANG Module"]
pub mod iana_igp_metric_types;
#[cfg(feature = "iana-ioam-integrity-protection-methods")]
#[doc = "iana-ioam-integrity-protection-methods YANG Module"]
pub mod iana_ioam_integrity_protection_methods;
#[cfg(feature = "iana-ipv4-special-registry")]
#[doc = "IPv4 Special-Purpose Address Space"]
pub mod iana_ipv4_special_registry;
#[cfg(feature = "iana-ipv6-ext-types")]
#[doc = "iana-ipv6-ext-types YANG Module"]
pub mod iana_ipv6_ext_types;
#[cfg(feature = "iana-ipv6-special-registry")]
#[doc = "IPv6 Special-Purpose Address Space"]
pub mod iana_ipv6_special_registry;
#[cfg(feature = "iana-msd-types")]
#[doc = "iana-msd-types YANG Module"]
pub mod iana_msd_types;
#[cfg(feature = "iana-ospf-functional-cap-bits")]
#[doc = "iana-ospf-functional-cap-bits YANG Module"]
pub mod iana_ospf_functional_cap_bits;
#[cfg(feature = "iana-pseudowire-types")]
#[doc = "iana-pseudowire-types YANG Module"]
pub mod iana_pseudowire_types;
#[cfg(feature = "iana-routing-types")]
#[doc = "iana-routing-types YANG Module"]
pub mod iana_routing_types;
#[cfg(feature = "iana-sip-option-tags")]
#[doc = "iana-sip-option-tags YANG Module"]
pub mod iana_sip_option_tags;
#[cfg(feature = "iana-ssh-encryption-algs")]
#[doc = "iana-ssh-encryption-algs YANG Module"]
pub mod iana_ssh_encryption_algs;
#[cfg(feature = "iana-ssh-key-exchange-algs")]
#[doc = "iana-ssh-key-exchange-algs YANG Module"]
pub mod iana_ssh_key_exchange_algs;
#[cfg(feature = "iana-ssh-mac-algs")]
#[doc = "iana-ssh-mac-algs YANG Module"]
pub mod iana_ssh_mac_algs;
#[cfg(feature = "iana-ssh-public-key-algs")]
#[doc = "iana-ssh-public-key-algs YANG Module"]
pub mod iana_ssh_public_key_algs;
#[cfg(feature = "iana-tls-cipher-suite-algs")]
#[doc = "iana-tls-cipher-suite-algs YANG Module"]
pub mod iana_tls_cipher_suite_algs;
#[cfg(feature = "iana-tunnel-type")]
#[doc = "iana-tunnel-type YANG Module"]
pub mod iana_tunnel_type;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "iana-as-numbers-special-registry")]
    crate::RegistryGroup {
        id: "iana-as-numbers-special-registry",
        title: "Special-Purpose Autonomous System (AS) Numbers",
        registries: iana_as_numbers_special_registry::REGISTRIES,
    },
    #[cfg(feature = "iana-bfd-types")]
    crate::RegistryGroup {
        id: "iana-bfd-types",
        title: "iana-bfd-types YANG Module",
        registries: iana_bfd_types::REGISTRIES,
    },
    #[cfg(feature = "iana-bgp-l2-encaps")]
    crate::RegistryGroup {
        id: "iana-bgp-l2-encaps",
        title: "iana-bgp-l2-encaps YANG Module",
        registries: iana_bgp_l2_encaps::REGISTRIES,
    },
    #[cfg(feature = "iana-crypt-hash")]
    crate::RegistryGroup {
        id: "iana-crypt-hash",
        title: "iana-crypt-hash YANG Module",
        registries: iana_crypt_hash::REGISTRIES,
    },
    #[cfg(feature = "iana-dns-class-rr-type")]
    crate::RegistryGroup {
        id: "iana-dns-class-rr-type",
        title: "iana-dns-class-rr-type YANG Module",
        registries: iana_dns_class_rr_type::REGISTRIES,
    },
    #[cfg(feature = "iana-dots-signal-channel")]
    crate::RegistryGroup {
        id: "iana-dots-signal-channel",
        title: "iana-dots-signal-channel YANG Module",
        registries: iana_dots_signal_channel::REGISTRIES,
    },
    #[cfg(feature = "iana-hardware")]
    crate::RegistryGroup {
        id: "iana-hardware",
        title: "iana-hardware YANG Module",
        registries: iana_hardware::REGISTRIES,
    },
    #[cfg(feature = "iana-http-versions")]
    crate::RegistryGroup {
        id: "iana-http-versions",
        title: "iana-http-versions YANG Module",
        registries: iana_http_versions::REGISTRIES,
    },
    #[cfg(feature = "iana-icmpv4-types")]
    crate::RegistryGroup {
        id: "iana-icmpv4-types",
        title: "iana-icmpv4-types YANG Module",
        registries: iana_icmpv4_types::REGISTRIES,
    },
    #[cfg(feature = "iana-icmpv6-types")]
    crate::RegistryGroup {
        id: "iana-icmpv6-types",
        title: "iana-icmpv6-types YANG Module",
        registries: iana_icmpv6_types::REGISTRIES,
    },
    #[cfg(feature = "iana-if-type")]
    crate::RegistryGroup {
        id: "iana-if-type",
        title: "iana-if-type YANG Module",
        registries: iana_if_type::REGISTRIES,
    },
    #[cfg(feature = "iana-igp-algo-types")]
    crate::RegistryGroup {
        id: "iana-igp-algo-types",
        title: "iana-igp-algo-types YANG Module",
        registries: iana_igp_algo_types::REGISTRIES,
    },
    #[cfg(feature = "iana-igp-link-attr-apps")]
    crate::RegistryGroup {
        id: "iana-igp-link-attr-apps",
        title: "iana-igp-link-attr-apps YANG Module",
        registries: iana_igp_link_attr_apps::REGISTRIES,
    },
    #[cfg(feature = "iana-igp-metric-types")]
    crate::RegistryGroup {
        id: "iana-igp-metric-types",
        title: "iana-igp-metric-types YANG Module",
        registries: iana_igp_metric_types::REGISTRIES,
    },
    #[cfg(feature = "iana-ioam-integrity-protection-methods")]
    crate::RegistryGroup {
        id: "iana-ioam-integrity-protection-methods",
        title: "iana-ioam-integrity-protection-methods YANG Module",
        registries: iana_ioam_integrity_protection_methods::REGISTRIES,
    },
    #[cfg(feature = "iana-ipv4-special-registry")]
    crate::RegistryGroup {
        id: "iana-ipv4-special-registry",
        title: "IPv4 Special-Purpose Address Space",
        registries: iana_ipv4_special_registry::REGISTRIES,
    },
    #[cfg(feature = "iana-ipv6-ext-types")]
    crate::RegistryGroup {
        id: "iana-ipv6-ext-types",
        title: "iana-ipv6-ext-types YANG Module",
        registries: iana_ipv6_ext_types::REGISTRIES,
    },
    #[cfg(feature = "iana-ipv6-special-registry")]
    crate::RegistryGroup {
        id: "iana-ipv6-special-registry",
        title: "IPv6 Special-Purpose Address Space",
        registries: iana_ipv6_special_registry::REGISTRIES,
    },
    #[cfg(feature = "iana-msd-types")]
    crate::RegistryGroup {
        id: "iana-msd-types",
        title: "iana-msd-types YANG Module",
        registries: iana_msd_types::REGISTRIES,
    },
    #[cfg(feature = "iana-ospf-functional-cap-bits")]
    crate::RegistryGroup {
        id: "iana-ospf-functional-cap-bits",
        title: "iana-ospf-functional-cap-bits YANG Module",
        registries: iana_ospf_functional_cap_bits::REGISTRIES,
    },
    #[cfg(feature = "iana-pseudowire-types")]
    crate::RegistryGroup {
        id: "iana-pseudowire-types",
        title: "iana-pseudowire-types YANG Module",
        registries: iana_pseudowire_types::REGISTRIES,
    },
    #[cfg(feature = "iana-routing-types")]
    crate::RegistryGroup {
        id: "iana-routing-types",
        title: "iana-routing-types YANG Module",
        registries: iana_routing_types::REGISTRIES,
    },
    #[cfg(feature = "iana-sip-option-tags")]
    crate::RegistryGroup {
        id: "iana-sip-option-tags",
        title: "iana-sip-option-tags YANG Module",
        registries: iana_sip_option_tags::REGISTRIES,
    },
    #[cfg(feature = "iana-ssh-encryption-algs")]
    crate::RegistryGroup {
        id: "iana-ssh-encryption-algs",
        title: "iana-ssh-encryption-algs YANG Module",
        registries: iana_ssh_encryption_algs::REGISTRIES,
    },
    #[cfg(feature = "iana-ssh-key-exchange-algs")]
    crate::RegistryGroup {
        id: "iana-ssh-key-exchange-algs",
        title: "iana-ssh-key-exchange-algs YANG Module",
        registries: iana_ssh_key_exchange_algs::REGISTRIES,
    },
    #[cfg(feature = "iana-ssh-mac-algs")]
    crate::RegistryGroup {
        id: "iana-ssh-mac-algs",
        title: "iana-ssh-mac-algs YANG Module",
        registries: iana_ssh_mac_algs::REGISTRIES,
    },
    #[cfg(feature = "iana-ssh-public-key-algs")]
    crate::RegistryGroup {
        id: "iana-ssh-public-key-algs",
        title: "iana-ssh-public-key-algs YANG Module",
        registries: iana_ssh_public_key_algs::REGISTRIES,
    },
    #[cfg(feature = "iana-tls-cipher-suite-algs")]
    crate::RegistryGroup {
        id: "iana-tls-cipher-suite-algs",
        title: "iana-tls-cipher-suite-algs YANG Module",
        registries: iana_tls_cipher_suite_algs::REGISTRIES,
    },
    #[cfg(feature = "iana-tunnel-type")]
    crate::RegistryGroup {
        id: "iana-tunnel-type",
        title: "iana-tunnel-type YANG Module",
        registries: iana_tunnel_type::REGISTRIES,
    },
];
