// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 2;
pub const REGISTRY_COUNT: usize = 6;
#[cfg(feature = "gss-api-parameters")]
#[doc = "Generic Security Service Application Program Interface Parameters"]
pub mod gss_api;
#[cfg(feature = "gss-eap-parameters")]
#[doc = "The Extensible Authentication Protocol Mechanism for the Generic Security Service Application Programming Interface (GSS-EAP) Parameters"]
pub mod gss_eap;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "gss-api-parameters")]
    crate::RegistryGroup {
        id: "gss-api-parameters",
        title: "Generic Security Service Application Program Interface Parameters",
        registries: gss_api::REGISTRIES,
    },
    #[cfg(feature = "gss-eap-parameters")]
    crate::RegistryGroup {
        id: "gss-eap-parameters",
        title: "The Extensible Authentication Protocol Mechanism for the Generic Security Service Application Programming Interface (GSS-EAP) Parameters",
        registries: gss_eap::REGISTRIES,
    },
];
