// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 10;
pub const REGISTRY_COUNT: usize = 20;
#[cfg(feature = "gsmpv3-adapt")]
#[doc = "Global Switch Management Protocol version 3 (GSMPv3) Adaptation Type Name Space"]
pub mod gsmpv3_adapt;
#[cfg(feature = "gsmpv3-event")]
#[doc = "Global Switch Management Protocol version 3 (GSMPv3) Event Flag Name Space"]
pub mod gsmpv3_event;
#[cfg(feature = "gsmpv3-failure")]
#[doc = "Global Switch Management Protocol version 3 (GSMPv3) Failure Response Message Name Space"]
pub mod gsmpv3_failure;
#[cfg(feature = "gsmpv3-label")]
#[doc = "Global Switch Management Protocol version 3 (GSMPv3) Label Type Name Space"]
pub mod gsmpv3_label;
#[cfg(feature = "gsmpv3-message")]
#[doc = "Global Switch Management Protocol version 3 (GSMPv3) Message Type Name Space"]
pub mod gsmpv3_message;
#[cfg(feature = "gsmpv3-model")]
#[doc = "Global Switch Management Protocol version 3 (GSMPv3) Model Type Name Space"]
pub mod gsmpv3_model;
#[cfg(feature = "gsmpv3-port")]
#[doc = "Global Switch Management Protocol version 3 (GSMPv3) Port Type Name Space"]
pub mod gsmpv3_port;
#[cfg(feature = "gsmpv3-result")]
#[doc = "Global Switch Management Protocol version 3 (GSMPv3) Result Type Name Space"]
pub mod gsmpv3_result;
#[cfg(feature = "gsmpv3-service")]
#[doc = "Global Switch Management Protocol version 3 (GSMPv3) Service ID Name Space"]
pub mod gsmpv3_service;
#[cfg(feature = "gsmpv3-traffic")]
#[doc = "Global Switch Management Protocol version 3 (GSMPv3) Traffic Control Name Space"]
pub mod gsmpv3_traffic;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "gsmpv3-adapt")]
    crate::RegistryGroup {
        id: "gsmpv3-adapt",
        title: "Global Switch Management Protocol version 3 (GSMPv3) Adaptation Type Name Space",
        registries: gsmpv3_adapt::REGISTRIES,
    },
    #[cfg(feature = "gsmpv3-event")]
    crate::RegistryGroup {
        id: "gsmpv3-event",
        title: "Global Switch Management Protocol version 3 (GSMPv3) Event Flag Name Space",
        registries: gsmpv3_event::REGISTRIES,
    },
    #[cfg(feature = "gsmpv3-failure")]
    crate::RegistryGroup {
        id: "gsmpv3-failure",
        title: "Global Switch Management Protocol version 3 (GSMPv3) Failure Response Message Name Space",
        registries: gsmpv3_failure::REGISTRIES,
    },
    #[cfg(feature = "gsmpv3-label")]
    crate::RegistryGroup {
        id: "gsmpv3-label",
        title: "Global Switch Management Protocol version 3 (GSMPv3) Label Type Name Space",
        registries: gsmpv3_label::REGISTRIES,
    },
    #[cfg(feature = "gsmpv3-message")]
    crate::RegistryGroup {
        id: "gsmpv3-message",
        title: "Global Switch Management Protocol version 3 (GSMPv3) Message Type Name Space",
        registries: gsmpv3_message::REGISTRIES,
    },
    #[cfg(feature = "gsmpv3-model")]
    crate::RegistryGroup {
        id: "gsmpv3-model",
        title: "Global Switch Management Protocol version 3 (GSMPv3) Model Type Name Space",
        registries: gsmpv3_model::REGISTRIES,
    },
    #[cfg(feature = "gsmpv3-port")]
    crate::RegistryGroup {
        id: "gsmpv3-port",
        title: "Global Switch Management Protocol version 3 (GSMPv3) Port Type Name Space",
        registries: gsmpv3_port::REGISTRIES,
    },
    #[cfg(feature = "gsmpv3-result")]
    crate::RegistryGroup {
        id: "gsmpv3-result",
        title: "Global Switch Management Protocol version 3 (GSMPv3) Result Type Name Space",
        registries: gsmpv3_result::REGISTRIES,
    },
    #[cfg(feature = "gsmpv3-service")]
    crate::RegistryGroup {
        id: "gsmpv3-service",
        title: "Global Switch Management Protocol version 3 (GSMPv3) Service ID Name Space",
        registries: gsmpv3_service::REGISTRIES,
    },
    #[cfg(feature = "gsmpv3-traffic")]
    crate::RegistryGroup {
        id: "gsmpv3-traffic",
        title: "Global Switch Management Protocol version 3 (GSMPv3) Traffic Control Name Space",
        registries: gsmpv3_traffic::REGISTRIES,
    },
];
