// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 5;
#[doc = "C-DNS DNS Capture Format"]
pub mod c_dns;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "c-dns",
    title: "C-DNS DNS Capture Format",
    registries: c_dns::REGISTRIES,
}];
