// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 4;
#[doc = "Protocol to Access White-Space (PAWS)"]
pub mod paws;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "paws",
    title: "Protocol to Access White-Space (PAWS)",
    registries: paws::REGISTRIES,
}];
