// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 47;
#[doc = "Multimedia Internet KEYing (MIKEY) Payload Name Spaces"]
pub mod mikey_payloads;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "mikey-payloads",
    title: "Multimedia Internet KEYing (MIKEY) Payload Name Spaces",
    registries: mikey_payloads::REGISTRIES,
}];
