// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "DetNet Associated Channel Header (d-ACH) Flags"]
pub mod detnet_ach_flags;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "detnet-ach-flags",
    title: "DetNet Associated Channel Header (d-ACH) Flags",
    registries: detnet_ach_flags::REGISTRIES,
}];
