// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 3;
#[doc = "IPSECKEY Resource Record Parameters"]
pub mod ipseckey_rr;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "ipseckey-rr-parameters",
    title: "IPSECKEY Resource Record Parameters",
    registries: ipseckey_rr::REGISTRIES,
}];
