// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "Network Layer Protocol Identifiers (NLPIDs) of Interest"]
pub mod nlpids;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "nlpids",
    title: "Network Layer Protocol Identifiers (NLPIDs) of Interest",
    registries: nlpids::REGISTRIES,
}];
