// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 10;
#[doc = "Internet Printing Protocol (IPP) Registrations"]
pub mod ipp_registrations;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "ipp-registrations",
    title: "Internet Printing Protocol (IPP) Registrations",
    registries: ipp_registrations::REGISTRIES,
}];
