// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 38;
#[doc = "Mobile IPv6 parameters"]
pub mod mobility;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "mobility-parameters",
    title: "Mobile IPv6 parameters",
    registries: mobility::REGISTRIES,
}];
