// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 3;
#[doc = "Preparation and Comparison of Internationalized Strings (PRECIS) Parameters"]
pub mod precis;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "precis-parameters",
    title: "Preparation and Comparison of Internationalized Strings (PRECIS) Parameters",
    registries: precis::REGISTRIES,
}];
