// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "Message Tracking Query Protocol (MTQP) Options Registry"]
pub mod mtqp_options;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "mtqp-options",
    title: "Message Tracking Query Protocol (MTQP) Options Registry",
    registries: mtqp_options::REGISTRIES,
}];
