// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 5;
#[doc = "Content Disposition Values and Parameters"]
pub mod cont_disp;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "cont-disp",
    title: "Content Disposition Values and Parameters",
    registries: cont_disp::REGISTRIES,
}];
