// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 2;
pub const REGISTRY_COUNT: usize = 4;
#[cfg(feature = "tzdist-actions")]
#[doc = "Time Zone Data Distribution Service (TZDIST) Service Actions"]
pub mod tzdist_actions;
#[cfg(feature = "tzdist-identifiers")]
#[doc = "Time Zone Data Distribution Service (TZDIST) Identifiers"]
pub mod tzdist_identifiers;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "tzdist-actions")]
    crate::RegistryGroup {
        id: "tzdist-actions",
        title: "Time Zone Data Distribution Service (TZDIST) Service Actions",
        registries: tzdist_actions::REGISTRIES,
    },
    #[cfg(feature = "tzdist-identifiers")]
    crate::RegistryGroup {
        id: "tzdist-identifiers",
        title: "Time Zone Data Distribution Service (TZDIST) Identifiers",
        registries: tzdist_identifiers::REGISTRIES,
    },
];
