// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 2;
pub const REGISTRY_COUNT: usize = 4;
#[cfg(feature = "lang-subtags-templates")]
#[doc = "Language Subtag Registration Form Archive"]
pub mod lang_subtags_templates;
#[cfg(feature = "lang-tag-apps")]
#[doc = "Language Tag Registration Form Archive (OBSOLETE)"]
pub mod lang_tag_apps;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "lang-subtags-templates")]
    crate::RegistryGroup {
        id: "lang-subtags-templates",
        title: "Language Subtag Registration Form Archive",
        registries: lang_subtags_templates::REGISTRIES,
    },
    #[cfg(feature = "lang-tag-apps")]
    crate::RegistryGroup {
        id: "lang-tag-apps",
        title: "Language Tag Registration Form Archive (OBSOLETE)",
        registries: lang_tag_apps::REGISTRIES,
    },
];
