// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "PIDF-LO Civic Address Considerations Registry"]
pub mod pidf_lo_civic_address_considerations;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "pidf-lo-civic-address-considerations",
    title: "PIDF-LO Civic Address Considerations Registry",
    registries: pidf_lo_civic_address_considerations::REGISTRIES,
}];
