// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 7;
pub const REGISTRY_COUNT: usize = 45;
#[cfg(feature = "dns-parameters")]
#[doc = "Domain Name System (DNS) Parameters"]
pub mod dns;
#[cfg(feature = "dns-key-rr")]
#[doc = "DNS KEY Resource Record Protocol Octet Values"]
pub mod dns_key_rr;
#[cfg(feature = "dns-sec-alg-numbers")]
#[doc = "Domain Name System Security (DNSSEC) Algorithm Numbers"]
pub mod dns_sec_alg_numbers;
#[cfg(feature = "dns-sshfp-rr-parameters")]
#[doc = "DNS SSHFP Resource Record Parameters"]
pub mod dns_sshfp_rr;
#[cfg(feature = "dns-svcb")]
#[doc = "DNS Service Bindings (SVCB)"]
pub mod dns_svcb;
#[cfg(feature = "dnskey-flags")]
#[doc = "DNSKEY FLAGS"]
pub mod dnskey_flags;
#[cfg(feature = "dnssec-nsec3-parameters")]
#[doc = "Domain Name System Security (DNSSEC) NextSECure3 (NSEC3) Parameters"]
pub mod dnssec_nsec3;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "dns-key-rr")]
    crate::RegistryGroup {
        id: "dns-key-rr",
        title: "DNS KEY Resource Record Protocol Octet Values",
        registries: dns_key_rr::REGISTRIES,
    },
    #[cfg(feature = "dns-parameters")]
    crate::RegistryGroup {
        id: "dns-parameters",
        title: "Domain Name System (DNS) Parameters",
        registries: dns::REGISTRIES,
    },
    #[cfg(feature = "dns-sec-alg-numbers")]
    crate::RegistryGroup {
        id: "dns-sec-alg-numbers",
        title: "Domain Name System Security (DNSSEC) Algorithm Numbers",
        registries: dns_sec_alg_numbers::REGISTRIES,
    },
    #[cfg(feature = "dns-sshfp-rr-parameters")]
    crate::RegistryGroup {
        id: "dns-sshfp-rr-parameters",
        title: "DNS SSHFP Resource Record Parameters",
        registries: dns_sshfp_rr::REGISTRIES,
    },
    #[cfg(feature = "dns-svcb")]
    crate::RegistryGroup {
        id: "dns-svcb",
        title: "DNS Service Bindings (SVCB)",
        registries: dns_svcb::REGISTRIES,
    },
    #[cfg(feature = "dnskey-flags")]
    crate::RegistryGroup {
        id: "dnskey-flags",
        title: "DNSKEY FLAGS",
        registries: dnskey_flags::REGISTRIES,
    },
    #[cfg(feature = "dnssec-nsec3-parameters")]
    crate::RegistryGroup {
        id: "dnssec-nsec3-parameters",
        title: "Domain Name System Security (DNSSEC) NextSECure3 (NSEC3) Parameters",
        registries: dnssec_nsec3::REGISTRIES,
    },
];
