// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 3;
#[doc = "SMTP MTA Strict Transport Security (MTA-STS)"]
pub mod mta_sts;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "mta-sts",
    title: "SMTP MTA Strict Transport Security (MTA-STS)",
    registries: mta_sts::REGISTRIES,
}];
