// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 8;
#[doc = "Cisco Service Level Assurance Protocol"]
pub mod cisco_sla_protocol;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "cisco-sla-protocol",
    title: "Cisco Service Level Assurance Protocol",
    registries: cisco_sla_protocol::REGISTRIES,
}];
