// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "Intrusion Detection Exchange Protocol (IDXP) Options"]
pub mod idxp_options;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "idxp-options",
    title: "Intrusion Detection Exchange Protocol (IDXP) Options",
    registries: idxp_options::REGISTRIES,
}];
