// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 7;
#[doc = "Media Resource Control Protocol Version 2 (MRCPv2) Parameters"]
pub mod mrcpv2;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "mrcpv2-parameters",
    title: "Media Resource Control Protocol Version 2 (MRCPv2) Parameters",
    registries: mrcpv2::REGISTRIES,
}];
