// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "Route Distinguisher Type Field"]
pub mod route_distinguisher_types;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "route-distinguisher-types",
    title: "Route Distinguisher Type Field",
    registries: route_distinguisher_types::REGISTRIES,
}];
