// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "Location-to-Service Translation (LoST) Location Profiles"]
pub mod lost_location_profiles;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "lost-location-profiles",
    title: "Location-to-Service Translation (LoST) Location Profiles",
    registries: lost_location_profiles::REGISTRIES,
}];
