// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 2;
pub const REGISTRY_COUNT: usize = 6;
#[cfg(feature = "language-subtag-registry")]
#[doc = "Language Subtag Registry"]
pub mod language_subtag_registry;
#[cfg(feature = "language-subtags-tags-extensions")]
#[doc = "Language Subtags, Tag Extensions, and Tags"]
pub mod language_subtags_tags_extensions;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "language-subtag-registry")]
    crate::RegistryGroup {
        id: "language-subtag-registry",
        title: "Language Subtag Registry",
        registries: language_subtag_registry::REGISTRIES,
    },
    #[cfg(feature = "language-subtags-tags-extensions")]
    crate::RegistryGroup {
        id: "language-subtags-tags-extensions",
        title: "Language Subtags, Tag Extensions, and Tags",
        registries: language_subtags_tags_extensions::REGISTRIES,
    },
];
