// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 5;
#[doc = "Real Time Streaming Protocol (RTSP)/1.0 Parameters"]
pub mod rtsp;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "rtsp-parameters",
    title: "Real Time Streaming Protocol (RTSP)/1.0 Parameters",
    registries: rtsp::REGISTRIES,
}];
