// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "Extensible Markup Language (XML) Configuration Access Protocol (XCAP) Parameters"]
pub mod xcap;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "xcap-parameters",
    title: "Extensible Markup Language (XML) Configuration Access Protocol (XCAP) Parameters",
    registries: xcap::REGISTRIES,
}];
