// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 21;
#[doc = "Host Identity Protocol (HIP) Parameters"]
pub mod hip;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "hip-parameters",
    title: "Host Identity Protocol (HIP) Parameters",
    registries: hip::REGISTRIES,
}];
