// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "Signaling Compression (SigComp) Registry"]
pub mod sigcomp_namespace;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "sigcomp-namespace",
    title: "Signaling Compression (SigComp) Registry",
    registries: sigcomp_namespace::REGISTRIES,
}];
