// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 12;
#[doc = "Protocol Independent Multicast (PIM) Parameters"]
pub mod pim;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "pim-parameters",
    title: "Protocol Independent Multicast (PIM) Parameters",
    registries: pim::REGISTRIES,
}];
