// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 16;
#[doc = "Internet Group Management Protocol (IGMP) Type Numbers"]
pub mod igmp_type_numbers;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "igmp-type-numbers",
    title: "Internet Group Management Protocol (IGMP) Type Numbers",
    registries: igmp_type_numbers::REGISTRIES,
}];
