// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 3;
pub const REGISTRY_COUNT: usize = 33;
#[cfg(feature = "isis-mt-parameters")]
#[doc = "IS-IS Multi-Topology Parameters"]
pub mod isis_mt;
#[cfg(feature = "isis-pdu")]
#[doc = "IS-IS PDU Registry"]
pub mod isis_pdu;
#[cfg(feature = "isis-tlv-codepoints")]
#[doc = "IS-IS TLV Codepoints"]
pub mod isis_tlv_codepoints;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "isis-mt-parameters")]
    crate::RegistryGroup {
        id: "isis-mt-parameters",
        title: "IS-IS Multi-Topology Parameters",
        registries: isis_mt::REGISTRIES,
    },
    #[cfg(feature = "isis-pdu")]
    crate::RegistryGroup {
        id: "isis-pdu",
        title: "IS-IS PDU Registry",
        registries: isis_pdu::REGISTRIES,
    },
    #[cfg(feature = "isis-tlv-codepoints")]
    crate::RegistryGroup {
        id: "isis-tlv-codepoints",
        title: "IS-IS TLV Codepoints",
        registries: isis_tlv_codepoints::REGISTRIES,
    },
];
