// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 3;
#[doc = "Unidirectional Lightweight Encapsulation (ULE) Next-Header Registry"]
pub mod ule_next_headers;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "ule-next-headers",
    title: "Unidirectional Lightweight Encapsulation (ULE) Next-Header Registry",
    registries: ule_next_headers::REGISTRIES,
}];
