// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 15;
#[doc = "EAP-AKA and EAP-SIM Parameters"]
pub mod eapsimaka_numbers;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "eapsimaka-numbers",
    title: "EAP-AKA and EAP-SIM Parameters",
    registries: eapsimaka_numbers::REGISTRIES,
}];
