// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 20;
#[doc = "Authentication and Authorization for Constrained Environments (ACE)"]
pub mod ace;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "ace",
    title: "Authentication and Authorization for Constrained Environments (ACE)",
    registries: ace::REGISTRIES,
}];
