// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 2;
pub const REGISTRY_COUNT: usize = 16;
#[cfg(feature = "emergency-call-additional-data")]
#[doc = "Emergency Call Additional Data"]
pub mod emergency_call_additional_data;
#[cfg(feature = "emergency-call-metadata-control-data")]
#[doc = "Emergency Call Metadata/Control Data"]
pub mod emergency_call_metadata_control_data;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "emergency-call-additional-data")]
    crate::RegistryGroup {
        id: "emergency-call-additional-data",
        title: "Emergency Call Additional Data",
        registries: emergency_call_additional_data::REGISTRIES,
    },
    #[cfg(feature = "emergency-call-metadata-control-data")]
    crate::RegistryGroup {
        id: "emergency-call-metadata-control-data",
        title: "Emergency Call Metadata/Control Data",
        registries: emergency_call_metadata_control_data::REGISTRIES,
    },
];
