// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 40;
#[doc = "Control And Provisioning of Wireless Access Points (CAPWAP) Parameters"]
pub mod capwap;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "capwap-parameters",
    title: "Control And Provisioning of Wireless Access Points (CAPWAP) Parameters",
    registries: capwap::REGISTRIES,
}];
