// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 8;
pub const REGISTRY_COUNT: usize = 30;
#[cfg(feature = "ipv6-parameters")]
#[doc = "Internet Protocol Version 6 (IPv6) Parameters"]
pub mod ipv6;
#[cfg(feature = "ipv6-address-space")]
#[doc = "IPv6 Address Space"]
pub mod ipv6_address_space;
#[cfg(feature = "ipv6-anycast-addresses")]
#[doc = "IPv6 Anycast Address Space"]
pub mod ipv6_anycast_addresses;
#[cfg(feature = "ipv6-interface-ids")]
#[doc = "Reserved IPv6 Interface Identifiers"]
pub mod ipv6_interface_ids;
#[cfg(feature = "ipv6-multicast-addresses")]
#[doc = "IPv6 Multicast Address Space"]
pub mod ipv6_multicast_addresses;
#[cfg(feature = "ipv6-routeralert-values")]
#[doc = "IPv6 Router Alert Option Values"]
pub mod ipv6_routeralert_values;
#[cfg(feature = "ipv6-tla-assignments")]
#[doc = "IPv6 Top Level Aggregation Identifier Assignments"]
pub mod ipv6_tla_assignments;
#[cfg(feature = "ipv6-unicast-address-assignments")]
#[doc = "IPv6 Global Unicast Address Space"]
pub mod ipv6_unicast_address_assignments;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "ipv6-address-space")]
    crate::RegistryGroup {
        id: "ipv6-address-space",
        title: "IPv6 Address Space",
        registries: ipv6_address_space::REGISTRIES,
    },
    #[cfg(feature = "ipv6-anycast-addresses")]
    crate::RegistryGroup {
        id: "ipv6-anycast-addresses",
        title: "IPv6 Anycast Address Space",
        registries: ipv6_anycast_addresses::REGISTRIES,
    },
    #[cfg(feature = "ipv6-interface-ids")]
    crate::RegistryGroup {
        id: "ipv6-interface-ids",
        title: "Reserved IPv6 Interface Identifiers",
        registries: ipv6_interface_ids::REGISTRIES,
    },
    #[cfg(feature = "ipv6-multicast-addresses")]
    crate::RegistryGroup {
        id: "ipv6-multicast-addresses",
        title: "IPv6 Multicast Address Space",
        registries: ipv6_multicast_addresses::REGISTRIES,
    },
    #[cfg(feature = "ipv6-parameters")]
    crate::RegistryGroup {
        id: "ipv6-parameters",
        title: "Internet Protocol Version 6 (IPv6) Parameters",
        registries: ipv6::REGISTRIES,
    },
    #[cfg(feature = "ipv6-routeralert-values")]
    crate::RegistryGroup {
        id: "ipv6-routeralert-values",
        title: "IPv6 Router Alert Option Values",
        registries: ipv6_routeralert_values::REGISTRIES,
    },
    #[cfg(feature = "ipv6-tla-assignments")]
    crate::RegistryGroup {
        id: "ipv6-tla-assignments",
        title: "IPv6 Top Level Aggregation Identifier Assignments",
        registries: ipv6_tla_assignments::REGISTRIES,
    },
    #[cfg(feature = "ipv6-unicast-address-assignments")]
    crate::RegistryGroup {
        id: "ipv6-unicast-address-assignments",
        title: "IPv6 Global Unicast Address Space",
        registries: ipv6_unicast_address_assignments::REGISTRIES,
    },
];
