// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 6;
#[doc = "Licklider Transmission Protocol (LTP) Parameters"]
pub mod ltp;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "ltp-parameters",
    title: "Licklider Transmission Protocol (LTP) Parameters",
    registries: ltp::REGISTRIES,
}];
