// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 12;
#[doc = "General Internet Signalling Transport (GIST) Parameters"]
pub mod gist;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "gist-parameters",
    title: "General Internet Signalling Transport (GIST) Parameters",
    registries: gist::REGISTRIES,
}];
