// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 17;
#[doc = "Internet Key Exchange (IKE) Attributes"]
pub mod ipsec_registry;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "ipsec-registry",
    title: "Internet Key Exchange (IKE) Attributes",
    registries: ipsec_registry::REGISTRIES,
}];
