// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 5;
#[doc = "Differentiated Services Field Codepoints (DSCP)"]
pub mod dscp_registry;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "dscp-registry",
    title: "Differentiated Services Field Codepoints (DSCP)",
    registries: dscp_registry::REGISTRIES,
}];
