// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 3;
#[doc = "WebRTC-HTTP Ingestion Protocol (WHIP)"]
pub mod whip;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "whip",
    title: "WebRTC-HTTP Ingestion Protocol (WHIP)",
    registries: whip::REGISTRIES,
}];
