// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 32;
#[doc = "Stream Control Transmission Protocol (SCTP) Parameters"]
pub mod sctp;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "sctp-parameters",
    title: "Stream Control Transmission Protocol (SCTP) Parameters",
    registries: sctp::REGISTRIES,
}];
