// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 4;
#[doc = "System for Cross-domain Identity Management (SCIM) Schema URIs"]
pub mod scim;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "scim",
    title: "System for Cross-domain Identity Management (SCIM) Schema URIs",
    registries: scim::REGISTRIES,
}];
