// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 3;
pub const REGISTRY_COUNT: usize = 21;
#[cfg(feature = "cbor-encoded-x509-c509")]
#[doc = "CBOR Encoded X.509 (C509)"]
pub mod cbor_encoded_x509_c509;
#[cfg(feature = "cbor-simple-values")]
#[doc = "Concise Binary Object Representation (CBOR) Simple Values"]
pub mod cbor_simple_values;
#[cfg(feature = "cbor-tags")]
#[doc = "Concise Binary Object Representation (CBOR) Tags"]
pub mod cbor_tags;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "cbor-encoded-x509-c509")]
    crate::RegistryGroup {
        id: "cbor-encoded-x509-c509",
        title: "CBOR Encoded X.509 (C509)",
        registries: cbor_encoded_x509_c509::REGISTRIES,
    },
    #[cfg(feature = "cbor-simple-values")]
    crate::RegistryGroup {
        id: "cbor-simple-values",
        title: "Concise Binary Object Representation (CBOR) Simple Values",
        registries: cbor_simple_values::REGISTRIES,
    },
    #[cfg(feature = "cbor-tags")]
    crate::RegistryGroup {
        id: "cbor-tags",
        title: "Concise Binary Object Representation (CBOR) Tags",
        registries: cbor_tags::REGISTRIES,
    },
];
