// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 5;
#[doc = "Timed Efficient Stream Loss-tolerant Authentication (TESLA) Parameters"]
pub mod tesla;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "tesla-parameters",
    title: "Timed Efficient Stream Loss-tolerant Authentication (TESLA) Parameters",
    registries: tesla::REGISTRIES,
}];
