// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 6;
pub const REGISTRY_COUNT: usize = 92;
#[cfg(feature = "sip-parameters")]
#[doc = "Session Initiation Protocol (SIP) Parameters"]
pub mod sip;
#[cfg(feature = "sip-clf-parameters")]
#[doc = "Session Initiation Protocol (SIP) Common Log Format (CLF) Parameters"]
pub mod sip_clf;
#[cfg(feature = "sip-events")]
#[doc = "Session Initiation Protocol (SIP) Event Types Namespace"]
pub mod sip_events;
#[cfg(feature = "sip-precond-types")]
#[doc = "Precondition Types Used with Session Initiation Protocol (SIP)"]
pub mod sip_precond_types;
#[cfg(feature = "sip-priv-values")]
#[doc = "Session Initiation Protocol (SIP) Privacy Header Values"]
pub mod sip_priv_values;
#[cfg(feature = "sip-table")]
#[doc = "Registry for the Session Initiation Protocol (SIP) NAPTR Resource Record Services Field"]
pub mod sip_table;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "sip-clf-parameters")]
    crate::RegistryGroup {
        id: "sip-clf-parameters",
        title: "Session Initiation Protocol (SIP) Common Log Format (CLF) Parameters",
        registries: sip_clf::REGISTRIES,
    },
    #[cfg(feature = "sip-events")]
    crate::RegistryGroup {
        id: "sip-events",
        title: "Session Initiation Protocol (SIP) Event Types Namespace",
        registries: sip_events::REGISTRIES,
    },
    #[cfg(feature = "sip-parameters")]
    crate::RegistryGroup {
        id: "sip-parameters",
        title: "Session Initiation Protocol (SIP) Parameters",
        registries: sip::REGISTRIES,
    },
    #[cfg(feature = "sip-precond-types")]
    crate::RegistryGroup {
        id: "sip-precond-types",
        title: "Precondition Types Used with Session Initiation Protocol (SIP)",
        registries: sip_precond_types::REGISTRIES,
    },
    #[cfg(feature = "sip-priv-values")]
    crate::RegistryGroup {
        id: "sip-priv-values",
        title: "Session Initiation Protocol (SIP) Privacy Header Values",
        registries: sip_priv_values::REGISTRIES,
    },
    #[cfg(feature = "sip-table")]
    crate::RegistryGroup {
        id: "sip-table",
        title: "Registry for the Session Initiation Protocol (SIP) NAPTR Resource Record Services Field",
        registries: sip_table::REGISTRIES,
    },
];
