// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "Open Network Computing (ONC) Remote Procedure Call (RPC) Network Identifiers"]
pub mod oncrpc_ids;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "oncrpc-ids",
    title: "Open Network Computing (ONC) Remote Procedure Call (RPC) Network Identifiers",
    registries: oncrpc_ids::REGISTRIES,
}];
