// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 2;
pub const REGISTRY_COUNT: usize = 5;
#[cfg(feature = "version-numbers")]
#[doc = "IP Version Numbers"]
pub mod version_numbers;
#[cfg(feature = "version-symbols")]
#[doc = "'version' symbols used within the ISUP and QSIG"]
pub mod version_symbols;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "version-numbers")]
    crate::RegistryGroup {
        id: "version-numbers",
        title: "IP Version Numbers",
        registries: version_numbers::REGISTRIES,
    },
    #[cfg(feature = "version-symbols")]
    crate::RegistryGroup {
        id: "version-symbols",
        title: "'version' symbols used within the ISUP and QSIG",
        registries: version_symbols::REGISTRIES,
    },
];
