// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 4;
#[doc = "Scalable Adaptive Multicast (SAM) Baseline"]
pub mod sam_baseline;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "sam-baseline",
    title: "Scalable Adaptive Multicast (SAM) Baseline",
    registries: sam_baseline::REGISTRIES,
}];
