// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "Pronet 80 Type Numbers"]
pub mod pronet80_type_numbers;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "pronet80-type-numbers",
    title: "Pronet 80 Type Numbers",
    registries: pronet80_type_numbers::REGISTRIES,
}];
