// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "Common Presence and Instant Messaging (CPIM) Headers"]
pub mod cpim_headers;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "cpim-headers",
    title: "Common Presence and Instant Messaging (CPIM) Headers",
    registries: cpim_headers::REGISTRIES,
}];
