// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "X.25 Type Numbers"]
pub mod x25_type_numbers;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "x25-type-numbers",
    title: "X.25 Type Numbers",
    registries: x25_type_numbers::REGISTRIES,
}];
