// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 3;
#[doc = "Bidirectional Forwarding Detection (BFD) Parameters"]
pub mod bfd;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "bfd-parameters",
    title: "Bidirectional Forwarding Detection (BFD) Parameters",
    registries: bfd::REGISTRIES,
}];
