// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "Per Hop Behavior Identification Codes"]
pub mod phbid_codes;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "phbid-codes",
    title: "Per Hop Behavior Identification Codes",
    registries: phbid_codes::REGISTRIES,
}];
