// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const FAMILY_COUNT: usize = 69;
pub const GROUP_COUNT: usize = 114;
pub const REGISTRY_COUNT: usize = 649;
