// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 61;
#[doc = "Authentication, Authorization, and Accounting (AAA) Parameters"]
pub mod aaa;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "aaa-parameters",
    title: "Authentication, Authorization, and Accounting (AAA) Parameters",
    registries: aaa::REGISTRIES,
}];
