// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 4;
#[doc = "Virtual Network Computing (VNC) Uniform Resource Identifier (URI)"]
pub mod vnc_uri;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "vnc-uri",
    title: "Virtual Network Computing (VNC) Uniform Resource Identifier (URI)",
    registries: vnc_uri::REGISTRIES,
}];
