// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 4;
#[doc = "Cryptographically Generated Addresses (CGA) Message Type Name Space"]
pub mod cga_message_types;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "cga-message-types",
    title: "Cryptographically Generated Addresses (CGA) Message Type Name Space",
    registries: cga_message_types::REGISTRIES,
}];
