// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "Java Message Service (JMS) URI Scheme Variants"]
pub mod jms_uri_variants;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "jms-uri-variants",
    title: "Java Message Service (JMS) URI Scheme Variants",
    registries: jms_uri_variants::REGISTRIES,
}];
