// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 6;
#[doc = "Multicast Address Dynamic Client Allocation Protocol (MADCAP) Parameters"]
pub mod madcap;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "madcap-parameters",
    title: "Multicast Address Dynamic Client Allocation Protocol (MADCAP) Parameters",
    registries: madcap::REGISTRIES,
}];
