// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 2;
pub const REGISTRY_COUNT: usize = 7;
#[cfg(feature = "rtcp-xr-block-types")]
#[doc = "RTP Control Protocol Extended Reports (RTCP XR) Block Type Registry"]
pub mod rtcp_xr_block_types;
#[cfg(feature = "rtcp-xr-sdp-parameters")]
#[doc = "RTP Control Protocol Extended Reports (RTCP XR) Session Description Protocol (SDP) Parameters Registry"]
pub mod rtcp_xr_sdp;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "rtcp-xr-block-types")]
    crate::RegistryGroup {
        id: "rtcp-xr-block-types",
        title: "RTP Control Protocol Extended Reports (RTCP XR) Block Type Registry",
        registries: rtcp_xr_block_types::REGISTRIES,
    },
    #[cfg(feature = "rtcp-xr-sdp-parameters")]
    crate::RegistryGroup {
        id: "rtcp-xr-sdp-parameters",
        title: "RTP Control Protocol Extended Reports (RTCP XR) Session Description Protocol (SDP) Parameters Registry",
        registries: rtcp_xr_sdp::REGISTRIES,
    },
];
