// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 7;
#[doc = "Simple Network Management Protocol (SNMP) Number Spaces"]
pub mod snmp_number_spaces;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "snmp-number-spaces",
    title: "Simple Network Management Protocol (SNMP) Number Spaces",
    registries: snmp_number_spaces::REGISTRIES,
}];
