// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "Bandwidth Constraints Model Identifiers"]
pub mod bandwidth_constraints_model_ids;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "bandwidth-constraints-model-ids",
    title: "Bandwidth Constraints Model Identifiers",
    registries: bandwidth_constraints_model_ids::REGISTRIES,
}];
