// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 48;
#[doc = "Internet Control Message Protocol version 6 (ICMPv6) Parameters"]
pub mod icmpv6;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "icmpv6-parameters",
    title: "Internet Control Message Protocol version 6 (ICMPv6) Parameters",
    registries: icmpv6::REGISTRIES,
}];
