// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 3;
pub const REGISTRY_COUNT: usize = 31;
#[cfg(feature = "tls-parameters")]
#[doc = "Transport Layer Security (TLS) Parameters"]
pub mod tls;
#[cfg(feature = "tls-ech-configuration-extensions")]
#[doc = "TLS Encrypted Client Hello (ECH) Configuration Extensions"]
pub mod tls_ech_configuration_extensions;
#[cfg(feature = "tls-extensiontype-values")]
#[doc = "Transport Layer Security (TLS) Extensions"]
pub mod tls_extensiontype_values;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "tls-ech-configuration-extensions")]
    crate::RegistryGroup {
        id: "tls-ech-configuration-extensions",
        title: "TLS Encrypted Client Hello (ECH) Configuration Extensions",
        registries: tls_ech_configuration_extensions::REGISTRIES,
    },
    #[cfg(feature = "tls-extensiontype-values")]
    crate::RegistryGroup {
        id: "tls-extensiontype-values",
        title: "Transport Layer Security (TLS) Extensions",
        registries: tls_extensiontype_values::REGISTRIES,
    },
    #[cfg(feature = "tls-parameters")]
    crate::RegistryGroup {
        id: "tls-parameters",
        title: "Transport Layer Security (TLS) Parameters",
        registries: tls::REGISTRIES,
    },
];
