// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 1;
#[doc = "Printer MIB Interpreters Language Families - OBSOLETE"]
pub mod printer_language_numbers;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "printer-language-numbers",
    title: "Printer MIB Interpreters Language Families - OBSOLETE",
    registries: printer_language_numbers::REGISTRIES,
}];
