// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 2;
pub const REGISTRY_COUNT: usize = 20;
#[cfg(feature = "gmpls-sig-parameters")]
#[doc = "Generalized Multi-Protocol Label Switching (GMPLS) Signaling Parameters"]
pub mod gmpls_sig;
#[cfg(feature = "gmpls-wson")]
#[doc = "GMPLS Routing Parameters for WSON"]
pub mod gmpls_wson;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "gmpls-sig-parameters")]
    crate::RegistryGroup {
        id: "gmpls-sig-parameters",
        title: "Generalized Multi-Protocol Label Switching (GMPLS) Signaling Parameters",
        registries: gmpls_sig::REGISTRIES,
    },
    #[cfg(feature = "gmpls-wson")]
    crate::RegistryGroup {
        id: "gmpls-wson",
        title: "GMPLS Routing Parameters for WSON",
        registries: gmpls_wson::REGISTRIES,
    },
];
