// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 19;
pub const REGISTRY_COUNT: usize = 54;
#[cfg(feature = "http-parameters")]
#[doc = "Hypertext Transfer Protocol (HTTP) Parameters"]
pub mod http;
#[cfg(feature = "http2-parameters")]
#[doc = "Hypertext Transfer Protocol version 2 (HTTP/2) Parameters"]
pub mod http2;
#[cfg(feature = "http3-parameters")]
#[doc = "Hypertext Transfer Protocol version 3 (HTTP/3)"]
pub mod http3;
#[cfg(feature = "http-alt-svc-parameters")]
#[doc = "Hypertext Transfer Protocol (HTTP) Alt-Svc Parameter Registry"]
pub mod http_alt_svc;
#[cfg(feature = "http-authentication-control-parameters")]
#[doc = "Hypertext Transfer Protocol (HTTP) Authentication Control Parameters"]
pub mod http_authentication_control;
#[cfg(feature = "http-authschemes")]
#[doc = "Hypertext Transfer Protocol (HTTP) Authentication Scheme Registry"]
pub mod http_authschemes;
#[cfg(feature = "http-cache-directives")]
#[doc = "Hypertext Transfer Protocol (HTTP) Cache Directive Registry"]
pub mod http_cache_directives;
#[cfg(feature = "http-cache-status")]
#[doc = "Hypertext Transfer Protocol (HTTP) Cache-Status"]
pub mod http_cache_status;
#[cfg(feature = "http-dig-alg")]
#[doc = "Hypertext Transfer Protocol (HTTP) Digest Algorithm Values"]
pub mod http_dig_alg;
#[cfg(feature = "http-digest-hash-alg")]
#[doc = "Hash Algorithms for HTTP Digest Fields"]
pub mod http_digest_hash_alg;
#[cfg(feature = "http-fields")]
#[doc = "Hypertext Transfer Protocol (HTTP) Field Name Registry"]
pub mod http_fields;
#[cfg(feature = "http-message-signature")]
#[doc = "HTTP Message Signature"]
pub mod http_message_signature;
#[cfg(feature = "http-methods")]
#[doc = "Hypertext Transfer Protocol (HTTP) Method Registry"]
pub mod http_methods;
#[cfg(feature = "http-priority")]
#[doc = "Hypertext Transfer Protocol (HTTP) Priority"]
pub mod http_priority;
#[cfg(feature = "http-problem-types")]
#[doc = "Hypertext Transfer Protocol (HTTP) Problem Types"]
pub mod http_problem_types;
#[cfg(feature = "http-proxy-status")]
#[doc = "Hypertext Transfer Protocol (HTTP) Proxy-Status"]
pub mod http_proxy_status;
#[cfg(feature = "http-status-codes")]
#[doc = "Hypertext Transfer Protocol (HTTP) Status Code Registry"]
pub mod http_status_codes;
#[cfg(feature = "http-upgrade-tokens")]
#[doc = "Hypertext Transfer Protocol (HTTP) Upgrade Token Registry"]
pub mod http_upgrade_tokens;
#[cfg(feature = "http-warn-codes")]
#[doc = "Hypertext Transfer Protocol (HTTP) Warn Codes"]
pub mod http_warn_codes;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "http-alt-svc-parameters")]
    crate::RegistryGroup {
        id: "http-alt-svc-parameters",
        title: "Hypertext Transfer Protocol (HTTP) Alt-Svc Parameter Registry",
        registries: http_alt_svc::REGISTRIES,
    },
    #[cfg(feature = "http-authentication-control-parameters")]
    crate::RegistryGroup {
        id: "http-authentication-control-parameters",
        title: "Hypertext Transfer Protocol (HTTP) Authentication Control Parameters",
        registries: http_authentication_control::REGISTRIES,
    },
    #[cfg(feature = "http-authschemes")]
    crate::RegistryGroup {
        id: "http-authschemes",
        title: "Hypertext Transfer Protocol (HTTP) Authentication Scheme Registry",
        registries: http_authschemes::REGISTRIES,
    },
    #[cfg(feature = "http-cache-directives")]
    crate::RegistryGroup {
        id: "http-cache-directives",
        title: "Hypertext Transfer Protocol (HTTP) Cache Directive Registry",
        registries: http_cache_directives::REGISTRIES,
    },
    #[cfg(feature = "http-cache-status")]
    crate::RegistryGroup {
        id: "http-cache-status",
        title: "Hypertext Transfer Protocol (HTTP) Cache-Status",
        registries: http_cache_status::REGISTRIES,
    },
    #[cfg(feature = "http-dig-alg")]
    crate::RegistryGroup {
        id: "http-dig-alg",
        title: "Hypertext Transfer Protocol (HTTP) Digest Algorithm Values",
        registries: http_dig_alg::REGISTRIES,
    },
    #[cfg(feature = "http-digest-hash-alg")]
    crate::RegistryGroup {
        id: "http-digest-hash-alg",
        title: "Hash Algorithms for HTTP Digest Fields",
        registries: http_digest_hash_alg::REGISTRIES,
    },
    #[cfg(feature = "http-fields")]
    crate::RegistryGroup {
        id: "http-fields",
        title: "Hypertext Transfer Protocol (HTTP) Field Name Registry",
        registries: http_fields::REGISTRIES,
    },
    #[cfg(feature = "http-message-signature")]
    crate::RegistryGroup {
        id: "http-message-signature",
        title: "HTTP Message Signature",
        registries: http_message_signature::REGISTRIES,
    },
    #[cfg(feature = "http-methods")]
    crate::RegistryGroup {
        id: "http-methods",
        title: "Hypertext Transfer Protocol (HTTP) Method Registry",
        registries: http_methods::REGISTRIES,
    },
    #[cfg(feature = "http-parameters")]
    crate::RegistryGroup {
        id: "http-parameters",
        title: "Hypertext Transfer Protocol (HTTP) Parameters",
        registries: http::REGISTRIES,
    },
    #[cfg(feature = "http-priority")]
    crate::RegistryGroup {
        id: "http-priority",
        title: "Hypertext Transfer Protocol (HTTP) Priority",
        registries: http_priority::REGISTRIES,
    },
    #[cfg(feature = "http-problem-types")]
    crate::RegistryGroup {
        id: "http-problem-types",
        title: "Hypertext Transfer Protocol (HTTP) Problem Types",
        registries: http_problem_types::REGISTRIES,
    },
    #[cfg(feature = "http-proxy-status")]
    crate::RegistryGroup {
        id: "http-proxy-status",
        title: "Hypertext Transfer Protocol (HTTP) Proxy-Status",
        registries: http_proxy_status::REGISTRIES,
    },
    #[cfg(feature = "http-status-codes")]
    crate::RegistryGroup {
        id: "http-status-codes",
        title: "Hypertext Transfer Protocol (HTTP) Status Code Registry",
        registries: http_status_codes::REGISTRIES,
    },
    #[cfg(feature = "http-upgrade-tokens")]
    crate::RegistryGroup {
        id: "http-upgrade-tokens",
        title: "Hypertext Transfer Protocol (HTTP) Upgrade Token Registry",
        registries: http_upgrade_tokens::REGISTRIES,
    },
    #[cfg(feature = "http-warn-codes")]
    crate::RegistryGroup {
        id: "http-warn-codes",
        title: "Hypertext Transfer Protocol (HTTP) Warn Codes",
        registries: http_warn_codes::REGISTRIES,
    },
    #[cfg(feature = "http2-parameters")]
    crate::RegistryGroup {
        id: "http2-parameters",
        title: "Hypertext Transfer Protocol version 2 (HTTP/2) Parameters",
        registries: http2::REGISTRIES,
    },
    #[cfg(feature = "http3-parameters")]
    crate::RegistryGroup {
        id: "http3-parameters",
        title: "Hypertext Transfer Protocol version 3 (HTTP/3)",
        registries: http3::REGISTRIES,
    },
];
