// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "Level of Assurance (LoA) Profiles"]
pub mod loa_profiles;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "loa-profiles",
    title: "Level of Assurance (LoA) Profiles",
    registries: loa_profiles::REGISTRIES,
}];
