// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "audio/telephone-event Parameters"]
pub mod audio_telephone_event_registry;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "audio-telephone-event-registry",
    title: "audio/telephone-event Parameters",
    registries: audio_telephone_event_registry::REGISTRIES,
}];
