// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 2;
#[doc = "Secret Key Transaction Authentication for DNS (TSIG) Algorithm Names"]
pub mod tsig_algorithm_names;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "tsig-algorithm-names",
    title: "Secret Key Transaction Authentication for DNS (TSIG) Algorithm Names",
    registries: tsig_algorithm_names::REGISTRIES,
}];
