// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 2;
pub const REGISTRY_COUNT: usize = 4;
#[cfg(feature = "urlauth-access-ids")]
#[doc = "Internet Message Access Protocol (IMAP) URLAUTH Access Identifiers and Prefixes"]
pub mod urlauth_access_ids;
#[cfg(feature = "urlauth-authorization-mechanism-registry")]
#[doc = "Internet Message Access Protocol (IMAP) URLAUTH Authorization Mechanism Registry"]
pub mod urlauth_authorization_mechanism_registry;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[
    #[cfg(feature = "urlauth-access-ids")]
    crate::RegistryGroup {
        id: "urlauth-access-ids",
        title: "Internet Message Access Protocol (IMAP) URLAUTH Access Identifiers and Prefixes",
        registries: urlauth_access_ids::REGISTRIES,
    },
    #[cfg(feature = "urlauth-authorization-mechanism-registry")]
    crate::RegistryGroup {
        id: "urlauth-authorization-mechanism-registry",
        title: "Internet Message Access Protocol (IMAP) URLAUTH Authorization Mechanism Registry",
        registries: urlauth_authorization_mechanism_registry::REGISTRIES,
    },
];
