// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by cargo run -p xtask -- iana generate.
pub const GROUP_COUNT: usize = 1;
pub const REGISTRY_COUNT: usize = 21;
#[doc = "Generic Associated Channel (G-ACh) Parameters"]
pub mod g_ach;
#[cfg(feature = "metadata")]
pub static GROUPS: &[crate::RegistryGroup] = &[crate::RegistryGroup {
    id: "g-ach-parameters",
    title: "Generic Associated Channel (G-ACh) Parameters",
    registries: g_ach::REGISTRIES,
}];
